/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //标点符号
    '.': '。',
    //标点符号结束

    //滚动新闻
    'Sorry, we are out of news for the day... try again later?': '抱歉，目前没有什么新闻……之后再来看看吧？',
    //滚动新闻结束

    //主菜单等
    'Loading...': '读取中……',
    'Help': '帮助(Discord频道)',
    'Main': '主界面',
    'Options': '选项',
    'Stats': '统计',
    'Achievements': '成就',
    'Energy': '能量',
    'Rockets': '火箭',
    'The Furnace': '熔炉',
    'Automation': '自动化',
    'Time Reversal': '时间反演',
    'Universal Collapse': '全体坍缩',
    'Pathogens': '病原体',
    'Dark Circle': '黑暗圆环',
    'Infinity': '无限',
    'Elementary': '基本粒子',
    'Req': '需要',
    'Req: Rank': '需要：级别',
    //主菜单等结束

    //选项
    'Saving': '保存选项',
    'Modes': '模式',
    'In-game': '游戏内',
    'Other': '其它',
    'Save': '保存',
    'Load': '读取',
    'Import': '导入',
    'Export': '导出',
    'HARD RESET': '硬重置',
    'Import All': '导入全部',
    'Export All': '导出全部',
    'AAU': '全成就',
    'Easy': '容易',
    'Absurd': '荒诞',
    'NA': '无成就',
    'Extreme': '极限',
    'Hard': '困难',
    'Hiker\'s Dream': '旅人之梦',
    '': '',
    '': '',
    '': '',
    '': '',
    'balanced up to endgame': '已平衡至游戏终点',
    '': '',
    'Activate Modes': '激活模式',
    'Dark Circle Pulsing: ON': '黑暗圆环脉动: 开启',
    'Dark Circle Pulsing: OFF': '黑暗圆环脉动: 关闭',
    'Elementary Confirmation: ON': '基本重置确认: 开启',
    'Elementary Confirmation: OFF': '基本重置确认: 关闭',
    'Theory Tree Display: GROUPS': '学说树显示方式: 群组',
    'Theory Tree Display: TREE': '学说树显示方式: 树状',
    'Exit Hadronic Chall Confirmation: ON': '退出强子挑战确认: 开启',
    'Exit Hadronic Chall Confirmation: OFF': '退出强子挑战确认: 关闭',
    'Significant Figures': '有效数字位数',
    'Notation: Scientific': '记数法: 科学',
    'Notation: Engineering': '记数法: 工程',
    'Notation: Standard': '记数法: 标准',
    'Notation: Mixed': '记数法: 混合',
    'Notation: Hexadecimal': '记数法: 十六进制',
    'Notation: Binary': '记数法: 二进制',
    'Notation: Symbols': '记数法: 符号',
    'Notation: Tetrational': '记数法: 迭代幂次',
    'Scientific': '科学',
    'Engineering': '工程',
    'Standard': '标准',
    'Mixed': '混合',
    'Hexadecimal': '十六进制',
    'Binary': '二进制',
    'Symbols': '符号',
    'Tetrational': '迭代幂次',
    'Font: Verdana': '字体: Verdana',
    'Font: Courier': '字体: Courier',
    'Font: Arial': '字体: Arial',
    'Font: Times': '字体: Times',
    'Font: Comic Sans MS': '字体: Comic Sans MS',
    'Theme: Normal': '主题: 普通',
    'Theme: Dark': '主题: 黑暗',
    'Normal': '普通',
    'Dark': '黑暗',
    'Rename Save': '重命名存档',
    'Hotkeys: ON': '快捷键: 开启',
    'Hotkeys: OFF': '快捷键: 关闭',
    'News Ticker: ON': '滚动新闻: 开启',
    'News Ticker: OFF': '滚动新闻: 关闭',
    'Feature Percentage: Logarithm': '百分比显示: 对数',
    'Feature Percentage: Linear': '百分比显示: 线性',
    'Logarithm': '对数',
    'Linear': '线性',
    'Imports: New Save': '导入选项: 新存档',
    'Imports: Overwrite': '导入选项: 覆盖存档',
    'New Save': '新存档',
    'Overwrite': '覆盖存档',
    'Auto-Save: ON': '自动保存: 开启',
    'Auto-Save: OFF': '自动保存: 关闭',
    'Hide Completed Ach Rows: ON': '隐藏已完成的成就行: 开启',
    'Hide Completed Ach Rows: OFF': '隐藏已完成的成就行: 关闭',
    'Visual Updates: Every Tick': '显示内容更新时间: 每个时刻',
    'Visual Updates: Every 2 Ticks': '显示内容更新时间: 每2个时刻',
    'Visual Updates: Every 5 Ticks': '显示内容更新时间: 每5个时刻',
    'Visual Updates: Every 20 Ticks': '显示内容更新时间: 每20个时刻',
    'Every Tick': '每个时刻',
    'Every 2 Ticks': '每2个时刻',
    'Every 5 Ticks': '每5个时刻',
    'Every 20 Ticks': '每20个时刻',
    'Notice: You are currently playing in v': '注意: 您目前的游戏版本为v',
    '. This game was inspired by ': '。此游戏的灵感来自于',
    'Antimatter Dimensions': '反物质维度',
    ' by Hevipelle, and it uses ': '(作者Hevipelle)，并使用了',
    ', none of which I take credit for. If you would like to create a mod of this game, that\'s fine, just give credit, let me know in the discord (preferrably with a game link), and name it something slightly different (like Distance Incremental NG+ or something of the sort)...': '，以上都是来自他人的成果。如果您想要制作本游戏的MOD，这是完全没问题的，您只需要保留原始作者的信息，在Discord内联系我(有游戏链接更佳)，并起个不同的名字(例如距离增量NG+或者其他什么的)即可……',
    'Changelog': '更新日志',
    'Distances': '距离单位',
    'Hotkeys': '快捷键',
    'Discord': 'Discord频道',
    'Donate': '捐赠赞助',
    //选项结束

    //统计
    'Scalings': '折算',
    'Rank/Tier Rewards': '级别/阶层的奖励',
    'Scaling Levels': '折算等级',
    'Scaled': '折算',
    'Superscaled': '超级折算',
    'Hyper': '究级折算',
    'Atomic': '原子折算',
    'Scaled ': '折算',
    'Superscaled ': '超级折算',
    'Hyper ': '究级折算',
    'Atomic ': '原子折算',
    //统计结束

    //成就
    'Not currently implemented.': '目前还未引入。',
    //成就结束

    //能量
    'The Generators': '发生器',
    'Cost': '花费',
    ' Motive': ' 动力',
    'Currently': '目前',
    'Currently: /': '目前：/',
    'Currently: +': '目前：+',
    'Currently: ^': '目前：^',
    'Optimization': '优化',
    'Endurance': '持久性',
    'Confidence': '信心',
    'Thrusters': '推进器',
    'Hill-Bending': '山脉倾斜',
    'The energy effect is boosted by your Motive': '根据动力数值，加强能量的效果',
    'Energy decreases slower based on your Motive': '根据动力数值，使能量减少得更慢',
    'Your Motive is higher based on the Incline': '根据斜度数值，使动力变得更高',
    'The Incline nerf to max velocity & acceleration is reduced based on your Rockets': '根据火箭数值，减少斜度对最大速度和加速度的惩罚',
    'All Energy Upgrades that are based on The Incline have a better incline in their effect': '“根据斜度数值”的所有能量升级中，斜度视为增加一定数值',
    'Optimization II': '优化 II',
    'Endurance II': '持久性 II',
    'Confidence II': '信心 II',
    'Thrusters II': '推进器 II',
    'Hill-Bending II': '山脉倾斜 II',
    'The above upgrade is stronger based on your Energy': '根据能量数值，使上方升级的效果变得更好',
    'The above upgrade is stronger based on your Total Motive': '根据动力总量，使上方升级的效果变得更好',
    'The above upgrade is stronger based on the Incline': '根据斜度数值，使上方升级的效果变得更好',
    'The above upgrade is stronger based on your Pathogens': '根据病原体数值，使上方升级的效果变得更好',
    'Optimization III': '优化 III',
    'Endurance III': '持久性 III',
    'Confidence III': '信心 III',
    'Thrusters III': '推进器 III',
    'Hill-Bending III': '山脉倾斜 III',
    'The above upgrade is stronger based on your Time Cubes': '根据时间方盒数值，使上方升级的效果变得更好',
    'Optimization IV': '优化 IV',
    'Endurance IV': '持久性 IV',
    'Confidence IV': '信心 IV',
    'Thrusters IV': '推进器 IV',
    'Omnipotence': '全能',
    'The above upgrade is stronger based on your Cadavers': '根据残骸数值，使上方升级的效果变得更好',
    'The above upgrade is stronger based on your Life Essence': '根据生命精华数值，使上方升级的效果变得更好',
    'All other upgrades in this row are stronger based on your Motive and Energy': '根据动力和能量数值，使此行其他所有升级的效果变得更好',
    'Omnipotence II': '全能 II',
    'Omnipotence III': '全能 III',
    'Omnipotence IV': '全能 IV',
    'Consistency': '坚实度',
    'Storage': '存储',
    ' is stronger based on your Super-Energy': ' 的效果根据超级能量数值变得更好',
    ' and ': ' 及 ',
    ' are stronger based on your Super-Energy': ' 的效果根据超级能量数值变得更好',
    'Your Motive cannot be lower than X, which is based on your Best-Ever Motive': '根据最高动力数值，使动力无法低于某个数值',
    'The Energy cap is increased based on your Best-Ever Motive': '根据最高动力数值，增加能量上限',
    'Energy Evolution': '能量进化',
    'Godlike': '如神',
    'Meta Omnipotence': '多元全能',
    'Super-Confidence': '超级信心',
    'Omnipotence V': '全能 V',
    'The Super Energy amount & first effect are raised to an exponent based on your Energy': '根据能量数值，使超级能量的数值及第一个效果增加为原来的某个指数',
    'Your Best Hadronic Score powers Optimization I and multiplies hadron gain': '您最高的强子分数使优化 I的效果变为原来的某个指数，并使强子的获取量乘以相应数值',
    'Super-Energy\'s second effect is stronger based on your Best-Ever Motive': '根据最高动力数值，使超级能量的第二个效果变得更好',
    'Your Motive is multiplied by your Hadrons': '使动力乘以强子的数值',
    'Omnipotence I-IV': '全能 I-IV',
    ' are stronger based on your Best Entropy': ' 的效果根据熵数值变得更好',
    'th root': '次方根',
    '% stronger': '%强化',
    'Generator': '发生器',
    'Respec The Generators': '洗点发生器',
    'Upgrade Generators': '升级发生器',
    'Buy a new Generator': '购买1个新的发生器',
    //能量结束

    //熔炉
    'Enhanced Furnace': '强化熔炉',
    'Magma Search': '岩浆搜索',
    'Plasma': '等离子体',
    ' Coal': ' 煤',
    'Level': '等级',
    'Reset all Furnace progress to gain a Blue Flame': '重置熔炉所有进度，获得1朵蓝色火焰',
    'Notice: Furnace Challenges will perform a Collapse reset. When in a Furnace Challenge, Furnace Upgrade': '注意：进行熔炉挑战将同时进行一次坍缩重置。在熔炉挑战中，熔炉升级',
    'does nothing': '失效',
    'is weaker': '效果减弱',
    'Blue Flame does nothing.': '蓝色火焰失效。',
    'Coal gain is raised to the power of 0.075 (before reduction': '煤的获取量变为原来的0.075次方(在减成之前生效',
    'Time Reversal Upgrade 16 does not affect Coal gain, and Hyper Furnace Upgrade scaling is stuck at 9,999% strength': '时间反演升级 16不影响煤的获取量，并且究级折算的熔炉升级一直为9999%的折算倍率',
    'Furnace Upgrade 1 does nothing, and the Blue Flame cost formula is faster': '熔炉升级 1失效，蓝色火焰花费的公式变得更糟糕',
    'All Coal generation boosts from outside The Furnace is disabled (which includes Time Speed), and Blue Flame is weaker': '所有除了熔炉以外能够加成煤产量的因子都失效(包括时间速度)，蓝色火焰效果变得更弱',
    'Furnace Upgrades are 99.99% weaker, Enhanced Furnace Upgrades are 50% weaker, and Blue Flame & Enhanced Furnace Upgrades cost scale much faster. This challenge forces an Elementary reset instead of a Collapse reset.': '熔炉升级效果减弱99.99%，强化熔炉升级效果减弱50%，蓝色火焰和强化熔炉升级的花费提升速度变得更快。进行此挑战将同时进行一次基本重置，而不是坍缩重置。',
    'Goal': '目标',
    ' Blue Flame': ' 蓝色火焰',
    'Complete': '完成',
    'Exit': '退出',
    'Finished': '已完成',
    'Start': '开始',
    'Reward: Superscaled & Hyper Furnace Upgrade scalings are 90% weaker.': '奖励：超级折算及究级折算的熔炉升级花费提升速度减少90%。',
    'Reward: Furnace Upgrade 1\'s effect is increased by 25x.': '奖励：熔炉升级 1的效果变为25倍。',
    'Reward: Scaled Rank Cheapener scaling is 90% weaker, and Knowledge gain is 3.2x faster.': '奖励：折算的级别降价器花费提升速度减少90%，知识的获取量变为3.2倍。',
    'Reward: The Extreme Mode reduction to pre-Infinity generation is less lethal (^0.75 -> ^': '奖励：极限模式无限之前内容的产量减成变得更缓和(从^0.75变为^',
    'Reward: Furnace Upgrade 4\'s effect is increased by 0.0001x for each Furnace Upgrade 1 bought, and unlock Furnace Upgrade': '奖励：每购买1次熔炉升级 1，熔炉升级 4的效果就增加0.0001倍，并解锁熔炉升级 ',
    'Reward: Blue Flame affects Enhanced Furnace Upgrades at a reduced rate': '奖励：蓝色火焰能够以较低的倍率使强化熔炉升级的效果变得更好',
    ' Enhanced Coal': ' 强化煤',
    'Add an extra level to the above upgrade': '使上方的升级额外增加1级',
    'Add two extra levels to the above upgrade': '使上方的升级额外增加2级',
    'Search for Magma': '搜索岩浆',
    'Reform your Magma': '重构岩浆',
    ' Magma & ': ' 岩浆及 ',
    ' Knowledge': ' 知识',
    'Note: This does not reset on Elementary.': '注意：这在基本重置时仍然保留。',
    //熔炉结束

    //自动化
    'Close up this robot.': '关闭此机器人。',
    'Open up Rankbot for improvements.': '开启级别机器人菜单。',
    'Open up Rank Cheapener-bot for improvements.': '开启级别降价器机器人菜单。',
    'Open up Tierbot for improvements.': '开启阶层机器人菜单。',
    'Open up Fuelbot for improvements.': '开启燃料机器人菜单。',
    'Max All': '最大化所有',
    'Interval': '间隔',
    'Magnitude': '数量',
    'Auto-Furnace': '自动熔炉',
    'Auto-Pathogens': '自动病原体升级',
    'Auto-Cores': '自动黑暗核心',
    'Auto-Robots': '自动机器人',
    'Auto-Infinity Upgrades': '自动无限升级',
    'Auto-Endorsements': '自动认可',
    'Auto-Perks': '自动特权',
    'Auto-Enlightenments': '自动启迪',
    'Auto-Spectral Gems': '自动幽冥宝石',
    'Auto-Derivative Boosts': '自动导数提升',
    'Auto-Elementaries': '自动基本重置',
    'Auto-Photon Upgrades': '自动光子升级',
    'Auto-Gluon Upgrades': '自动胶子升级',
    'Auto-Tree Upgrades': '自动学说树升级',
    'Auto-Theoretical Boosters': '自动学说增强器',
    'Auto-Foam Unlocks': '自动泡沫解锁',
    'Auto-Entropy': '自动熵',
    'Auto-Entropy Upgrades': '自动熵升级',
    'Mode': '模式',
    'AMOUNT': '数量',
    'TIME': '时间',
    //自动化结束

    //时间反演
    //时间反演结束

    //全体坍缩
    'Sacrifice all your cadavers into life essence.': '将所有残骸转化为生命精华。',
    'Time goes by 100x faster, but this gets weaker the further you go (minimum 2x, at 50Mpc).': '时间加快100倍，但随着游戏进度效果减少(最少为2倍，在50兆秒差距时达到此数值)。',
    'Time goes by faster.': '时间加快。',
    'Start with 10 Rockets on reset.': '重置时直接获得10个火箭。',
    'Start with 1 Rocket Fuel on reset.': '重置时直接获得1点火箭燃料',
    'Unlock Fuelbot, and Cadaver gain is boosted by Time Cubes.': '解锁燃料机器人，根据时间方盒数值，增加残骸的获取量。',
    'Gain 10x more Rockets.': '火箭的获取量变为10倍。',
    'Keep Time Reversal upgrades on reset.': '重置时保留时间反演升级。',
    'Time Speed multiplies Rocket gain at a reduced rate.': '时间速度以较低的倍率增加火箭的获取量。',
    'Gain 1% of Rocket gain every second (unaffected by Time Speed).': '每秒获得当前产量1%的火箭(不受时间速度影响)。',
    'Life Essence boosts Cadaver gain.': '根据生命精华数值，增加残骸的获取量。',
    'Tiers do not reset Ranks.': '阶层不再重置级别。',
    'Ranks do not reset anything.': '级别不再重置任何东西。',
    //全体坍缩结束

    //病原体
    'Time Reversal Upgrade 2 is boosted by your Pathogens.': '根据病原体数值，使时间反演升级 2的效果变得更好。',
    'Rocket gain is boosted by your Cadavers.': '根据残骸数值，增加火箭的获取量。',
    'Time Cube gain is boosted by your Cadavers.': '根据残骸数值，增加时间方盒的获取量。',
    'Maximum Velocity is boosted by your Pathogens.': '根据病原体数值，加强最大速度的效果。',
    'Boost Pathogen gain.': '增加病原体的获取量。',
    'The transfer from Cadavers to Life Essence is more efficient.': '将残骸转换为生命精华的转换率变得更高。',
    'The rocket gain softcap starts later.': '火箭获取量的软上限延迟出现。',
    'The rocket effect softcap starts later.': '火箭效果的软上限延迟出现。',
    'The cadaver gain softcap starts later.': '残骸获取量的软上限延迟出现。',
    'The cadaver effect softcap starts later.': '残骸效果的软上限延迟出现。',
    'Superscaled Rocket Fuel scaling starts later based on your Pathogens.': '根据病原体数值，使超级折算的火箭燃料延迟出现。',
    'Scaled Dark Core scaling starts later based on your Rocket Fuel.': '根据火箭燃料数值，使折算的黑暗核心延迟出现。',
    'Pathogen Upgrade 5 gets 2 extra Levels.': '病原体升级 5额外获得2级。',
    'Scaled & Superscaled Rank scalings are weaker based on your Dark Cores.': '根据黑暗核心数值，使折算和超级折算的级别花费提升速度减少。',
    'Scaled Endorsement scaling is slightly weaker.': '折算的认可花费提升速度略微减少。',
    //病原体结束

    //黑暗圆环
    //黑暗圆环结束

    //无限
    'Ascension': '飞升',
    'The Stadium': '竞技场',
    'The Pantheon': '万神殿',
    'Derivatives': '导数',
    'Endorsements': '认可',
    'Reset Infinity Upgrades': '重置无限升级',
    'Ranks & Tiers boost Time Speed.': '根据级别和阶层数值，增加时间速度。',
    'Knowledge boosts Rocket gain.': '根据知识数值，增加火箭的获取量。',
    'Start with the first 2 rows of Time Reversal upgrades on reset.': '重置时直接获得前两行的时间反演升级。',
    'Keep Time Reversal upgrades on reset.': '重置时保留时间反演升级。',
    'Scaled Tier scaling is 20% weaker.': '折算的阶层花费提升速度减少20%。',
    'Scaled Rank & Tier scaling starts 2 later.': '折算的级别和阶层延迟2次出现。',
    'Before any other boosts, Knowledge gain is raised to the power of 1.25.': '先于其他加成生效，将知识的获取量变为原来的1.25次方。',
    'Time Reversal Upgrade 11 is stronger based on your Accelerational Energy.': '根据加速能量数值，使时间反演升级 11的效果变得更好。',
    'inf9;7 is stronger based on your Tier.': '根据阶层数值，使无限9;7升级的效果变得更好。',
    'Hyper Tier scaling is weaker based on your Knowledge.': '根据知识数值，使究级折算的阶层花费提升速度减少。',
    'Knowledge boosts the Rocket effect.': '根据知识数值，使火箭的效果变得更好。',
    'Time Speed boosts Knowledge gain at a reduced rate.': '时间速度以较低的倍率增加知识的获取量',
    'Knowledge & Time Cubes synergize with one another.': '知识和时间方盒互相加强。',
    'Gain 1% of Cadaver gain every second.': '每秒获得当前产量1%的残骸。',
    'Superscaled Rank scaling is 5% weaker.': '超级折算的阶层花费提升速度减少5%。',
    'Superscaled Rocket Fuel scaling starts 5 later.': '超级折算的火箭燃料延迟5次出现。',
    'Scaled Tier scaling is weaker based on your Stadium Challenge completions.': '根据竞技场挑战完成数量，使折算的阶层花费提升速度减少。',
    'Base Knowledge gain is boosted by Heavenly Chips & Demonic Souls.': '根据天堂碎片和恶魔灵魂数值，增加知识的基础获取量。',
    'Unlock 5 new Pathogen Upgrades.': '解锁5个新的病原体升级。',
    'Superscaled Dark Core scaling starts 5 later, triple Base Knowledge gain, & before any other boosts, Knowledge gain is raised to the power of 1.15.': '超级折算的黑暗核心延迟5次出现。使知识的基础获取量变为3倍。先于其他加成生效，将知识的获取量变为原来的1.15次方。',
    'Start with all Collapse Milestones on reset.': '重置时直接获得所有坍缩里程碑。',
    'Knowledge & Cadavers synergize with one another.': '知识和残骸互相加强。',
    'Pathogen Upgrades are 10% stronger.': '病原体升级的效果增加10%。',
    'Unlock Auto-Pathogen upgrades.': '解锁自动病原体升级。',
    'Scaled Rocket Fuel scaling is 25% weaker.': '折算的火箭燃料花费提升速度减少25%。',
    'Pathogen Upgrades softcap 1 later.': '病原体升级的软上限延迟1次出现。',
    'Enlightenments boost Ascension Power gain.': '根据启迪数值，增加飞升能量的获取量。',
    'Pathogen Upgrades 6-10 use better formulas.': '病原体升级 6至10的公式变得更好。',
    'Ascension Power gain is boosted by your Rocket Fuel.': '根据火箭燃料数值，增加飞升能量的获取量。',
    'Robot Intervals boost Heavenly Chip gain.': '根据机器人的间隔数值，增加天堂碎片的获取量。',
    'Dark Flow is twice as fast.': '黑暗流翻倍。',
    'Unlock Auto-Dark Cores.': '解锁自动黑暗核心。',
    'Scaled Rank scaling is 50% weaker.': '折算的级别花费提升速度减少50%。',
    'Inf2;1, inf2;2, inf2;3, & inf3;2 are brought back if repealed.': '如果无限2;1升级，无限2;2升级，无限2;3升级和无限3;2升级被撤销了，则使它们重新生效。',
    'Scaled Pathogen Upgrade scaling starts 2 later.': '折算的病原体升级延迟2次出现。',
    'Time Speed boosts Acceleration & Maximum Velocity.': '根据时间速度数值，使加速度和最大速度变得更多。',
    'Life Essence multiplies Rocket gain.': '使火箭的获取量变为生命精华数值的倍数。',
    'Ranks & Tiers do not reset Derivatives beyond Acceleration.': '级别和阶层不再重置高于加速度的导数。',
    '\'The Universe Doesnt Exist\' reward is stronger based on your Elementaries.': '根据基本重置次数，使“宇之不存”成就的奖励变得更好。',
    'Pathogen Upgrades are 5% stronger.': '病原体升级的效果增加5%。',
    'Gain 10% of Life Essence gain every second.': '每秒获得当前产量10%的生命精华。',
    'Cadavers boost Knowledge gain.': '根据残骸数值，增加知识的获取量。',
    'Knowledge & Endorsements boost Dark Flow.': '根据知识和认可数值，加强黑暗流的效果。',
    'Perks last longer based on your Knowledge.': '根据知识数值，使特权持续更久。',
    'Superscaled Tier scaling starts later based on your Maximum Velocity.': '根据最大速度数值，使超级折算的阶层延迟出现。',
    'Rockets also boost Accelerational Energy.': '火箭还可以加强加速能量的效果。',
    'The Spectral Gem requirement starts earlier.': '减少幽冥宝石的需求。',
    'Higgs Bosons & Pathogen gain are synergized.': '希格斯玻色子和病原体互相加强。',
    'Scaled Rocket Fuel scaling starts 10 later.': '折算的火箭燃料延迟10次出现。',
    'Superscaled Rank scaling starts 5 later.': '超级折算的级别延迟5次出现。',
    'Pathogen Upgrades are 2.5% stronger.': '病原体升级的效果增加2.5%。',
    'Dark Cores scale 2 later.': '折算的黑暗核心延迟2次出现。',
    'Knowledge boosts Ascension Power gain.': '根据知识数值，增加飞升能量的获取量。',
    'Maximum Velocity boosts Acceleration, and you can activate 2 perks at once.': '最大速度还可以加强加速度的效果，您可以同时激活2个特权。',
    'Maximum Velocity is replaced by Velocital Energy.': '最大速度被替换为速度能量。',
    'Dark Matter & Dark Energy use better formulas.': '黑暗物质和黑暗能量的公式变得更好。',
    'Multipliers to Derivatives beyond Velocity are raised to the power of 4.': '高于速度的导数，其倍率变为原来的4次方。',
    'The Rocket effect exponent is multiplied by 16.': '火箭的效果指数乘以16。',
    'Stadium Challenge completions boost perks & make them last longer.': '竞技场挑战的完成次数可以加强特权的效果，并使它们持续更久。',
    'Ascension Power & Dark Flow have synergy.': '飞升能量和黑暗流互相加强。',
    'Start Infinities with Dark Circles unlocked.': '无限重置后直接解锁黑暗圆环。',
    'inf2;3 & inf3;2 are stronger based on your Pathogens.': '根据病原体数值，使无限2;3升级和无限3;2升级的效果变得更好。',
    'The fifth Pathogen Upgrade boosts itself.': '病原体升级 5强化自身。',
    'Dark Flow is increased by 20% for every Dark Core.': '每个黑暗核心使黑暗流增加20%。',
    'Unlock Accelerational Energy, which is created based on your Ranks & Tiers, and boosts your Velocital Energy, which in turn boosts your Time Speed.': '解锁加速能量，效果基于级别和阶层的数值，可以增加速度能量的效果，因此最终可以增加时间速度。',
    'Spectral Gems, Angels, & Demons boost Dark Flow.': '根据幽冥宝石，天使和恶魔数值，加强黑暗流的效果。',
    'Hyper Rank scaling is 2% weaker.': '究级折算的级别花费提升速度减少2%。',
    'The W Boson boost to Z Boson gain uses a better formula.': 'W玻色子对Z玻色子的获取量提升公式变得更好。',
    'The Dark Circle cycle reduction uses a much weaker formula.': '黑暗圆环的圆环间减成公式变得更缓和。',
    'Accelerational Energy & Purge Power gain are synergized.': '加速能量和净化能量互相加强。',
    'Heavenly Chip & Demonic Soul gain are boosted by Endorsements.': '根据认可数值，增加天堂碎片和恶魔灵魂的获取量。',
    'The Time Doesn\'t Exist reward softcap start is multiplied by your Purge Power ^17.': '时骨无存成就奖励的软上限变为某个数值的倍率，此数值为净化能量的17次方。',
    'The Cadaver effect softcap is 80% weaker.': '残骸效果的软上限效果减少80%。',
    'Scaled Dark Core & Hyper Rank scaling is weaker based on Endorsements.': '根据认可数值，使折算的黑暗核心及究级折算的级别花费提升速度减少。',
    'Scaled Pathogen Upgrade scaling is 84% weaker.': '折算的病原体升级花费提升速度减少84%。',
    'inf8;1 & inf3;8 are stronger based on your Purge Power.': '根据净化能量数值，使无限8;1升级和无限3;8升级的效果变得更好。',
    'Ascension Power gain is 10x faster.': '飞升能量的获取量变为10倍。',
    'Gauge Force uses a better formula to get its reward.': '规范作用力效果的公式变得更好。',
    'Jerk boosts Accelerational Energy & Knowledge gain.': '根据加加速度数值，使加速能量和知识的获取量变得更多。',
    'Derivative Shifts & Boosts add to the Rocket effect.': '导数变换和导数提升增加火箭的效果。',
    'Angels & Demons are synergized, and Scaled Endorsement scaling starts 1 later.': '天使和恶魔互相加强，且折算的认可延迟1次出现。',
    'Derivative Boosts boost Time Speed.': '导数提升还可以使时间速度的效果变得更好。',
    'Pathogen Upgrades are 1% stronger for every Endorsement you have.': '每有1点认可，病原体升级的效果就增加1%。',
    'Superscaled Rank & Tier scalings are weaker based on your Demonic Souls.': '根据恶魔灵魂数值，使超级折算的级别和阶层花费提升速度减少。',
    'Derivative Boosts give a better boost to Derivatives based on your Rank.': '根据级别数值，使导数提升的效果变得更好。',
    'Rocket gain is multiplied by (n+1)^0.1, where n is your Time Cubes (softcaps at higher values).': '火箭的获取量变为某个数值的倍率，此数值为(n+1)^0.1，其中n为时间方盒数值(在较高数值时达到软上限)。',
    'Knowledge gain is multiplied by (n+1)^0.2, where n is your Ascension Power.': '知识的获取量变为某个数值的倍率，此数值为(n+1)^0.2，其中n为飞升能量数值。',
    'Pathogen Upgrades are stronger based on your Scalar Bosons.': '根据标量玻色子数值，使病原体升级的效果变得更好。',
    'Superscaled Pathogen Upgrade scaling is weaker based on your Ascension Power, and Distance produces Snap at a reduced rate (unaffected by Time Speed).': '根据飞升能量数值，使超级折算的病原体升级花费提升速度减少。距离能够以较低的倍率产生加加加速度(不受时间速度的影响)。',
    'Velocital Energy boosts your Accelerational Energy at a reduced rate, and inf7;7\'s boost to Velocital Energy uses a better formula.': '速度能量能够以较低的倍率使加速能量的效果变得更好。无限7;7升级中，增加速度能量效果的公式变得更好。',
    'The Rocket effect also affects Time Speed.': '火箭的效果还可以影响时间速度。',
    'Robot Magnitudes boost Demonic Soul gain, and the Purge Power effect exponent is halved.': '根据机器人的数量数值，增加恶魔灵魂的获取量。净化能量的效果指数减半。',
    'Quarks boost Dark Flow & Pathogen gain.': '根据夸克数值，增加黑暗流和病原体的获取量。',
    'Leptons make Perks last longer.': '根据轻子数值，使特权持续更久。',
    'Hyper Rocket Fuel scaling starts 20 later.': '究级折算的火箭燃料延迟20次出现。',
    'The Perk Accelerator\'s boost to Perk Power uses a better formula.': '特权加速器增加特权效果的公式变得更好。',
    'Gravitons are gained 100x as fast.': '引力子的获取量变为100倍。',
    'Dark Flow & Pathogen gain are increased by 90% for every Rank you have & by 750% for every Tier you have.': '黑暗流和病原体的获取量按以下规则获得提升：每有1级别增加90%，每有1阶层增加750%。',
    'Reset Stadium completions': '重置竞技场完成情况',
    'Reset Second-Row Stadium completions': '重置第二行竞技场完成情况',
    'Exit Stadium Challenge': '退出竞技场挑战',
    'Note: Perks do nothing in Stadium Challenges': '注意：竞技场中特权失效',
    'Note 2: Each Challenge completion makes the others': '注意2：每完成一个挑战，都会使',
    ' in the same row': '同一行的',
    ' harder, with the exception being Reality, which actually gets easier.': '其他挑战变得更难，只有 现实 例外，它会变得更容易。',
    'Spaceon': '天奥',
    'Solaris': '索拉里斯',
    'Eternity': '永恒',
    'Reality': '现实',
    'Drigganiz': '德里格尼兹',
    'Flamis': '弗拉米斯',
    'Cranius': '克劳尼乌斯',
    'Spectra': '光谱',
    'Aqualon': '阿奎纶',
    'Nullum': '无效化',
    'Quantron': '康诚',
    'Respec Angels & Demons back into Spectral Gems': '洗点天使和恶魔变回幽冥宝石',
    'Transform one Spectral Gem into an Angel': '将1块幽冥宝石变为1个天使',
    'Transform one Spectral Gem into a Demon': '将1块幽冥宝石变为1个恶魔',
    'Distance': '距离',
    'Velocity': '速度',
    'Acceleration': '加速度',
    'Jerk': '加加速度',
    'Snap': '加加加速度',
    //无限结束

    //基本粒子
    'Fermions': '费米子',
    'Bosons': '玻色子',
    'Theories': '学说',
    'Hadronic Challenge': '强子挑战',
    'Quantum Foam': '量子泡沫',
    'Skyrmions': '斯格明子',
    'Transform one of your Elementary Particles into a Fermion': '将1个基本粒子变为费米子',
    'Transform 10% of your Elementary Particles into Fermions': '将10%的基本粒子变为费米子',
    'Transform 50% of your Elementary Particles into Fermions': '将50%的基本粒子变为费米子',
    'Transform 100% of your Elementary Particles into Fermions': '将100%的基本粒子变为费米子',
    'Hover to see current Quark effect': '鼠标停留此处以查看当前夸克效果',
    'Click to change Quark Type': '点击以改变夸克类型',
    'Hover to see current Lepton effect': '鼠标停留此处以查看当前轻子效果',
    'Click to change Lepton Type': '点击以改变轻子类型',
    'Transform one of your Elementary Particles into a Boson': '将1个基本粒子变为玻色子',
    'Transform 10% of your Elementary Particles into Bosons': '将10%的基本粒子变为玻色子',
    'Transform 50% of your Elementary Particles into Bosons': '将50%的基本粒子变为玻色子',
    'Transform 100% of your Elementary Particles into Bosons': '将100%的基本粒子变为玻色子',
    'Gauge Bosons': '规范玻色子',
    'Scalar Bosons': '标量玻色子',
    'Triple Pathogen gain': '将病原体的获取量变为3倍',
    'Boost Knowledge gain by': '知识的获取量增加',
    'Double Photon & Gluon gain': '光子和胶子的获取量翻倍',
    'Double Elementary Particle gain': '基本粒子的获取量翻倍',
    ' Photons': ' 光子',
    'Red': '红',
    'Green': '绿',
    'Blue': '蓝',
    'Anti-Red': '反红',
    'Anti-Green': '反绿',
    'Anti-Blue': '反蓝',
    'Double gain of the anti version of this colour.': '将此颜色反色的获取量翻倍',
    'Get ten free Theory Points.': '额外获得10点学说点数。',
    'Total: +': '合计：+',
    ' of these Gluons.': '该胶子。',
    'Always keep TR Upgrades, the Pathogen Upgrade automator, the Dark Core automator, & Furnace Challenge completions. You also start with Automation unlocked.': '永远保留时间反演升级，自动病原体，自动黑暗核心和熔炉挑战完成情况。自动化直接解锁。',
    'Always keep TR Upgrades, the Pathogen Upgrade automator, the Dark Core automator, and all energy upgrades. You also start with Automation unlocked.': '永远保留时间反演升级，自动病原体，自动黑暗核心和所有能量升级。自动化直接解锁。',
    'Unlock Auto-Robots, and your best motivation is not reset upon elementary.': '解锁自动机器人，基本重置不再重置最高动力。',
    'You start with 10 Endorsements on reset and raise Consistency to the 1.8th power.': '重置时直接获得10点认可，并将坚实度变为原来的1.8次方。',
    'Unlock Auto-Endorsements and boost Meta Omnipotence based on the square root of Higgs Upgrades.': '解锁自动认可，且根据希格斯升级数量的平方根，加强 多元全能 升级的效果。',
    'Unlock Auto-Spectral Gem Distribution, you keep Purge Power on reset, and super energy multiplies photons gain.': '解锁自动幽冥宝石，重置时保留净化能量，且使光子的获取量乘以超级能量的数值。',
    'Angels & Demons boost the Gauge Force effect and the second super energy effect.': '根据天使和恶魔数值，加强规范作用力的效果和超级能量的第二个效果',
    'Purge Power boosts Quark & Lepton gain and passive energy gain is squared.': '根据净化能量数值，增加夸克和轻子的获取量，且被动能量的获取量变为原来的平方。',
    'Always keep TR Upgrades, the Pathogen Upgrade automator, & the Dark Core automator. You also start with Automation unlocked.': '永远保留时间反演升级，自动病原体和自动黑暗核心。自动化直接解锁。',
    'Unlock Auto-Robots.': '解锁自动机器人。',
    'Unlock Auto-Infinity Upgrades, and Infinity Upgrades are never repealed.': '解锁自动无限升级，无限升级不会被撤销。',
    'You start with 10 Endorsements on reset.': '重置时直接获得10点认可。',
    'Unlock Auto-Endorsements.': '解锁自动认可。',
    'Unlock Auto-Enlightenments.': '解锁自动启迪。',
    'Quarks, Leptons, Photons, Gravitons, & Higgs Bosons boost Elementary Particle gain.': '根据夸克，轻子，光子，引力子和希格斯玻色子数值，增加基本粒子的获取量。',
    'Perks last 900% longer.': '特权持续时间增加900%。',
    'Unlock Auto-Perks & the Perk Accelerator.': '解锁自动特权和特权加速器。',
    'Endorsements beyond 36 boost Higgs Boson gain.': '根据超过36的认可数值，增加希格斯玻色子的获取量。',
    'Keep Stadium Challenges on reset, and Elementary Particle gain & Higgs Boson gain are increased by 10% for each Higgs Upgrade bought.': '重置时保留竞技场挑战，且每购买一个希格斯升级，基本粒子的获取量和希格斯玻色子的获取量就增加10%。',
    'Unlock Auto-Derivative Shifts/Boosts, Auto-Endorsements buy max, and you gain Knowledge 200% faster.': '解锁自动导数变换/提升，自动认可能够最大化进行购买，知识的获取量翻倍。',
    'Unlock Auto-Spectral Gem Distribution, and you keep Purge Power on reset.': '解锁自动幽冥宝石，重置时保留净化能量。',
    'Derivative Boosts are stronger based on your Higgs Bosons.': '根据希格斯玻色子数值，使导数提升的效果变得更好。',
    'Unlock 1 new row & column of Infinity Upgrades.': '解锁一行一列新的无限升级。',
    'Knowledge gain & Ascension Power gain are faster based on the Perk Accelerator\'s speed.': '根据特权加速器的速度数值，增加知识的获取量和飞升能量的获取量。',
    'Angels & Demons boost the Gauge Force effect.': '根据天使和恶魔数值，加强规范作用力的效果。',
    'Purge Power boosts Quark & Lepton gain.': '根据净化能量数值，增加夸克和轻子的获取量。',
    'inf10;4 uses a better formula.': '无限10;4升级的公式变得更好。',
    'Atomic Rank scaling starts later based on your Higgs Bosons.': '根据希格斯玻色子数值，使原子折算的级别延迟出现。',
    'inf10;10 uses a better formula.': '无限10;10升级的公式变得更好。',
    'Gain 666x more Gluons.': '胶子的获取量变为原来的666倍。',
    'The softcap to Pathogen Upgrade 1\'s effect is nerfed, and Pathogen Upgrade 1\'s formula is better.': '病原体升级 1的软上限效果减少，且病原体升级 1的公式变得更好。',
    'Unlock a new Furnace Challenge.': '解锁一个新的熔炉挑战。',
    'Both Molten Brick effects use better formulas.': '熔融砖块两个效果的公式变得更好。',
    'The final Enhanced Furnace Upgrade is stronger based on its level.': '根据强化熔炉的最后一个升级等级数值，使它的效果变得更好。',
    'Your Molten Bricks are doubled.': '熔融砖块翻倍。',
    'The Magma Search requirement scales half as fast, and Magma\'s effect uses a better formula.': '岩浆搜索的需求增长速度减半，岩浆效果的公式变得更好。',
    'Raise Optimization effect to the power of the number of Higgs Boson upgrades and energy multiples Knowledge gain.': '将 优化 升级的效果变为某个数值为幂的指数，此数值为希格斯玻色子升级数量，且使知识的获取量乘以能量的数值。',
    'Raise Storage to the tenth power and it also boosts Motivation.': '将 存储 升级变为原来的十次方，且它还可以使动力的效果变得更好。',
    'Square each Omnipotence and Storage': '使每个 全能 升级和 存储 升级变为原来的平方',
    'The Theoriverse': '学说宇宙',
    'Supersymmetry': '超对称理论',
    'The Theory Tree': '学说树',
    'Strings': '弦',
    'Preons': '前子',
    'Accelerons': '加速子',
    'Inflatons': '暴胀子',
    'Unlock Supersymmetry': '解锁超对称理论',
    'Cost: 1 Theory Point': '花费：1 学说点数',
    'Unlock The Theory Tree': '解锁学说树',
    'Cadavers': '残骸',
    'Pathogen Upgrades': '病原体升级',
    'Knowledge & Higgs': '知识及希格斯',
    'Theoriverse & Endorsements': '学说宇宙及认可',
    'Pantheon': '万神殿',
    'EP Gain & Elementaries': '基本粒子获取及基本重置',
    'Entangled Strings': '纠缠弦',
    'Hadrons': '强子',
    'Magma': '岩浆',
    'Misc.': '杂项',
    'Unlock Strings': '解锁弦',
    'Cost: 7 Theory Points': '花费：7 学说点数',
    'Unlock Preons': '解锁前子',
    'Cost: 10 Theory Points': '花费：10 学说点数',
    'Unlock Accelerons': '解锁加速子',
    'Cost: 84 Theory Points': '花费：84 学说点数',
    'Unlock Inflatons': '解锁暴胀子',
    'Cost: 1,600 Theory Points': '花费：1600 学说点数',
    'Clear Selector Data': '清除选择器数据',
    'Main Selectors': '主要选择器',
    'Pre-Collapse Selectors': '坍缩前选择器',
    'Collapse Selectors': '坍缩选择器',
    'Infinity Selectors': '无限选择器',
    'Elementary Selectors': '基本粒子选择器',
    'hover for info': '鼠标停留此处以查看详情',
    'Boosts': '加成',
    'Entropy': '熵',
    'Enlarge Quantum Foam by 1m in height': '将量子泡沫加高1米',
    'Enlarge Quantum Foam by 1m in width': '将量子泡沫加宽1米',
    'Enlarge Quantum Foam by 1m in depth': '将量子泡沫加深1米',
    'Unlock a new type of Foam': '解锁一种新的泡沫',
    'Enlarge Subplanck Foam by 1m in height': '将亚普朗克泡沫加高1米',
    'Enlarge Subplanck Foam by 1m in width': '将亚普朗克泡沫加宽1米',
    'Enlarge Subplanck Foam by 1m in depth': '将亚普朗克泡沫加深1米',
    'Enlarge Subspatial Foam by 1m in height': '将子空间泡沫加高1米',
    'Enlarge Subspatial Foam by 1m in width': '将子空间泡沫加宽1米',
    'Enlarge Subspatial Foam by 1m in depth': '将子空间泡沫加深1米',
    'Enlarge Infinitesimal Foam by 1m in height': '将无穷小泡沫加高1米',
    'Enlarge Infinitesimal Foam by 1m in width': '将无穷小泡沫加宽1米',
    'Enlarge Infinitesimal Foam by 1m in depth': '将无穷小泡沫加深1米',
    'Enlarge Protoversal Foam by 1m in height': '将太初泡沫加高1米',
    'Enlarge Protoversal Foam by 1m in width': '将太初泡沫加宽1米',
    'Enlarge Protoversal Foam by 1m in depth': '将太初泡沫加深1米',
    'Re-form your Protoversal Foam': '重构太初泡沫',
    ' Quantum Foam': ' 量子泡沫',
    ' Subplanck Foam': ' 亚普朗克泡沫',
    ' Subspatial Foam': ' 子空间泡沫',
    ' Infinitesimal Foam': ' 无穷小泡沫',
    ' Protoversal Foam': ' 太初泡沫',
    'Height': '高度',
    'Width': '宽度',
    'Depth': '深度',
    'Force Entropy Reset': '强制熵重置',
    'Unlock Auto-Foam Unlocks (in automation tab': '解锁自动泡沫解锁(在自动化页面',
    'Gain more of all types of Foam based on your Theoriverse completions': '根据学说宇宙的完成次数，增加所有类型的泡沫获取量',
    'Rocket Fuel boosts Entropy Gain': '根据火箭燃料数值，增加熵的获取量',
    'Hyper Pathogen Upgrade scaling starts later based on your Ω Particles': '根据Ω 粒子数值，使究级折算的病原体升级延迟出现',
    'Magma makes the Entropy effect stronger': '根据岩浆数值，加强熵的效果',
    'Theoretical Boosters make Ω Particles require less Entropy': '根据学说增强器数值，使Ω 粒子需要更少的熵来获取',
    'The "Actually Useless Theories" achievement reward uses a better formula': '“完全无用的学说”成就奖励的公式变得更好',
    'Ω Particles are stronger based on your Hadrons': '根据强子数值，加强Ω 粒子的效果',
    'Accelerons & Inflatons boost Entropy gain': '根据加速子和暴胀子数值，增加熵的获取量',
    'The Fermion Boost & the Inflaton Boost are 8.5% stronger': '费米子加成和暴胀子加成的效果增加8.5%',
    'Skyrmions make Ω Particles require less Entropy': '根据斯格明子数值，使Ω 粒子需要更少的熵来获取',
    'Unlock Auto-Entropy, and gain 50% more Entropy (kept on Skyrmion reset': '解锁自动熵，并且熵的获取量增加50%(斯格明子重置时保留',
    'Unlock Auto-Entropy Upgrades, and all Foam types are gained 10x faster (kept on Skyrmion reset': '解锁自动熵升级，所有类型的泡沫获取量变为10倍(斯格明子重置时保留',
    'Gain 1% of Elementary Particle, Fermion, & Boson gain every second (kept on Skyrmion reset': '每秒获得当前产量1%的基本粒子，费米子和玻色子(斯格明子重置时保留',
    'The Extreme mode nerf to pre-Infinity production is less lethal (^0.825 ->': '极限模式无限之前内容的产量减成变得更缓和(从^0.825变为^',
    'Buying Theory Tree Upgrades does not spend Theory Points, and the last Inflaton effect does not become extremely softcapped (kept on Skyrmion reset': '购买学说树升级不再花费学说点数，暴胀子的最后一个效果不再变为极端软上限(斯格明子重置时保留',
    'Entropy boosts Skyrmion gain': '根据熵数值，增加斯格明子的获取量',
    'Gauge Force\'s effect uses a much better formula': '规范作用力效果的公式变得更好',
    'Pions & Spinors make each other increase in cost 75% less (kept on Skyrmion reset': 'π介子和旋量使彼此的花费增加速度减少75%(斯格明子重置时保留',
    'The Plasma Exponent is boosted by your Best Entropy': '根据最高熵数值，增加等离子体的指数',
    'Unlock Auto-Theoretical Boosters, and Theoretical Boosters give many more Theory Points, but Theoretical Boosters are reset on Skyrmion reset (kept on Skyrmion reset': '解锁自动学说增强器，可以从学说增强器中获得更多学说点数，但学说增强器还是会在斯格明子重置时被重置的(斯格明子重置时保留',
    'The Perk Accelerator never goes Weakened or Broken, and the Hadron effect interval is smaller based on your Hadrons': '特权加速器不再有加速效果和中止效果，并且根据强子数值，减少强子获取学说点数的间隔',
    'The first Inflaton effect uses a better formula, Pions & Spinors do not make each other increase in cost, and you can buy max Pion/Spinor Fields (kept on Skyrmion reset': '暴胀子第一个效果的公式变得更好，π介子和旋量不再使彼此的花费增加，您可以最大化购买π介子场和旋量场(斯格明子重置时保留',
    'FU4 & EFU3 also multiply the upgrade\'s effect (but only at 20% upgrade power).': '熔炉升级 4和强化熔炉升级 3变为自身效果一定倍率(倍率为升级效果幂的20%)。',
    ' Entropy': ' 熵',
    'Pions': 'π介子',
    'Spinors': '旋量',
    'Reset Pion & Spinor Fields': '重置π介子场和旋量场',
    'Reset Pion Field': '重置π介子场',
    'Max Pion Field': '最大化π介子场',
    'Import Pion Field': '导入π介子场',
    'Export Pion Field': '导出π介子场',
    'Reset Spinor Field': '重置旋量场',
    'Max Spinor Field': '最大化旋量场',
    'Import Spinor Field': '导入旋量场',
    'Export Spinor Field': '导出旋量场',
    'All Rank/Tier scalings start later based on your Pions.': '根据π介子数值，使所有类型折算的级别和阶层延迟出现。',
    'Add to all Foam Boosts based on your Spinors.': '根据旋量数值，增加所有泡沫加成的效果。',
    'Pathogen Upgrades are stronger (unaffected by softcap).': '病原体升级的效果变得更好(不受软上限影响)。',
    'Graviton Boosts are stronger.': '引力子加成的效果变得更好。',
    'Skyrmions boost Purge Power gain.': '斯格明子还可以增加净化能量的获取量。',
    'Skyrmions boost Entropy gain.': '斯格明子还可以增加熵的获取量。',
    'The Cadaver effect is stronger.': '残骸的效果变得更好。',
    'The Skyrmion effect is stronger.': '斯格明子的效果变得更好。',
    'Skyrmions boost Dark Flow.': '斯格明子还可以加强黑暗流的效果。',
    'Skyrmions boost Supersymmetric Particle gain.': '斯格明子还可以增加超对称粒子的获取量。',
    'Ranks boost Pion & Spinor gain.': '级别还可以加成π介子和旋量的获取量。',
    'Elementary Particles boost Pion & Spinor gain.': '基本粒子还可以加成π介子和旋量的获取量。',
    'Derivative Boosts are stronger based on their amount.': '根据导数加成数值，使它们的效果变得更好。',
    'Ω Particles are stronger based on their amount.': '根据Ω 粒子数值，使它们的效果变得更好。',
    'All Spinor Upgrades are cheaper.': '所有旋量升级变得更便宜。',
    'All Pion Upgrades are cheaper.': '所有π介子升级变得更便宜。',
    'The "Time Doesnt Exist" effect is raised to an exponent.': '“时骨无存”的效果变为某个数值为幂的指数。',
    'The Entropy effect is raised to an exponent.': '熵的效果的效果变为某个数值为幂的指数。',
    'Tiers use a weaker cost formula, but only if they\'re not scaled in any way.': '阶层花费的公式更缓和，但不能是任何方式折算的阶层。',
    'Entropy uses a weaker requirement formula.': '熵需求的公式更缓和。',
    'Pathogen Upgrade 1\'s effect is multiplied.': '病原体升级 1的效果变为某个数值的倍数。',
    'Gauge Speed is raised to an exponent.': '规范作用力产生资源的速度变为某个数值为幂的指数。',
    'The Cadaver effect is raised to an exponent.': '残骸的效果变为某个数值为幂的指数。',
    'The Skyrmion effect is multiplied.': '斯格明子的效果变为某个数值的倍数。',
    'The Perk Accelerator is stronger based on your Inflatons.': '根据暴胀子数值，使特权加速器的效果变得更好。',
    'The second Inflaton effect is stronger based on your Ascension Power.': '根据飞升能量数值，使暴胀子的第二个效果变得更好。',
    'Dear Player,': '亲爱的玩家，',
    'Welp you\'ve done it, you\'ve reached the end of the multiverse!': '很好，您终于到达了多宇宙的终点！',
    'Sadly, more content won\'t be available for the time being...': '很遗憾的是，目前没有更多新内容了……',
    'For now, just try another mode or something, I dunno.': '现在，您可以考虑换个模式接着玩，或者是干脆换游戏，怎么样都行。',
    'Thanks for playing my game!': '总之，感谢您游玩我的游戏！',
    'From Jacorb': 'Jacord敬上',
    'P.S: If you\'re wondering why I put this message here, it\'s because it\'s prep for future content and because v2.0 may not be out for a while...': '如果您想知道这里为什么会有这么一条消息，原因是为了之后内容做准备，而且v2.0可能没那么快推出……',
    //基本粒子结束

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    ": ": "：",
    "\n": "",
    "\t\t\t\t\t\t\t\t\t\t": "",
    "\t\t\t\t\t\t\t\t\t": "",
    "\t\t\t\t\t\t\t\t": "",
    "\t\t\t\t\t\t\t": "",
    "\t\t\t\t\t\t": "",
    "\t\t\t\t\t": "",
    "\t\t\t\t": "",
    "\t\t\t": "",
    "\t\t": "",
    "\t": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "：",
    "： ": "：",
    ")": ")",
    "%": "%",
    "\n\t\t\t\t\t\t\t\t\t\t": "",
    "\n\t\t\t\t\t\t\t\t\t": "",
    "\n\t\t\t\t\t\t\t\t": "",
    "\n\t\t\t\t\t\t\t": "",
    "\n\t\t\t\t\t\t": "",
    "\n\t\t\t\t\t": "",
    "\n\t\t\t\t": "",
    "\n\t\t\t": "",
    "\n\t\t": "",
    "\n\t": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?\s\+$/, //处理数字
    /^打开微信扫一扫$/, //不抓取的内容
    /^点击加群$/, //不抓取的内容
    /^更多同类游戏$/, //不抓取的内容
    /^关注公众号$/, //不抓取的内容
    /^旧版$/, //不抓取的内容
    /^论坛$/, //不抓取的内容
    /^Git游戏$/, //不抓取的内容
    /^QQ群号$/, //不抓取的内容
    /^帮助(.*)$/, //不抓取的内容
    /^(.*)您(.*)$/, //不抓取的内容
    /^(.*)特权(.*)$/, //不抓取的内容
    /^(.*)启迪(.*)$/, //不抓取的内容
    /^(.*)使(.*)$/, //不抓取的内容
    /^(.*)将(.*)$/, //不抓取的内容
    /^(.*)点(.*)$/, //不抓取的内容
    /^(.*)子(.*)$/, //不抓取的内容
    /^(.*)为(.*)$/, //不抓取的内容
    /^(.*)加(.*)$/, //不抓取的内容
    /^(.*)上(.*)$/, //不抓取的内容
    /^(.*)下(.*)$/, //不抓取的内容
    /^(.*)粲(.*)$/, //不抓取的内容
    /^(.*)奇(.*)$/, //不抓取的内容
    /^(.*)顶(.*)$/, //不抓取的内容
    /^(.*)底(.*)$/, //不抓取的内容
    /^(.*)电(.*)$/, //不抓取的内容
    /^(.*)缪(.*)$/, //不抓取的内容
    /^(.*)陶(.*)$/, //不抓取的内容
    /^(.*)中微(.*)$/, //不抓取的内容
    /^(.*)振荡(.*)$/, //不抓取的内容
    /^(.*)普西(.*)$/, //不抓取的内容
    /^ ，因此(.*)$/, //不抓取的内容
    /^到达(.*)$/, //不抓取的内容
    /^无限(.*)$/, //不抓取的内容
    /^重置(.*)$/, //不抓取的内容
    /^(.*)的(.*)$/, //不抓取的内容
    /^(.*)地(.*)$/, //不抓取的内容
    /^(.*)得(.*)$/, //不抓取的内容
    /^(.*)倍(.*)$/, //不抓取的内容
    /^(.*)级(.*)$/, //不抓取的内容
    /^(.*)层(.*)$/, //不抓取的内容
    /^(.*)次(.*)$/, //不抓取的内容
    /^(.*)个(.*)$/, //不抓取的内容
    /^(.*)米(.*)$/, //不抓取的内容
    /^(.*)宇宙(.*)$/, //不抓取的内容
    /^(.*)秒(.*)$/, //不抓取的内容
    /^(.*)分(.*)$/, //不抓取的内容
    /^(.*)时(.*)$/, //不抓取的内容
    /^(.*)日(.*)$/, //不抓取的内容
    /^(.*)周(.*)$/, //不抓取的内容
    /^(.*)年(.*)$/, //不抓取的内容
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^Purchase the Rankbot for (.*) scraps.$/, '花费$1碎屑购买级别机器人'], //自动化
    [/^Purchase the Rank Cheapener-bot for (.*) scraps.$/, '花费$1碎屑购买级别降价器机器人'], //自动化
    [/^Purchase the Tierbot for (.*) scraps.$/, '花费$1碎屑购买阶层机器人'], //自动化
    [/^Purchase the Fuelbot for (.*) scraps.$/, '花费$1碎屑购买燃料机器人'], //自动化
]);