const ACH_DATA = {
	rows: 19,
	cols: 8,
	names: {
		11: "快速冲刺",
		12: "更好的鞋子",
		13: "魔鬼训练",
		14: "飞向太空！",
		15: "火箭冲击",
		16: "与人无关",
		17: "但您还是在前进。",
		18: "蓄意谋杀",

		21: "长途驾驶",
		22: "该换油了",
		23: "3是幸运数字",
		24: "又升空了？",
		25: "补充燃料",
		26: "自动化进化",
		27: "时者生存",
		28: "残骸如山",

		31: "土星公转",
		32: "加入假燃料",
		33: "IV测试",
		34: "既可十飞，何故单飞？",
		35: "三倍燃料",
		36: "自动化能量提升",
		37: "有这么多吗？",
		38: "心会很痛",

		41: "十秒视差",
		42: "狂风怒号",
		43: "就好这口",
		44: "这有意义吗？",
		45: "九千未满……",
		46: "磁铁的作用",
		47: "我全都要！",
		48: "超级聪明",

		51: "超凡脱俗",
		52: "滥箭充数",
		53: "2+2=10",
<<<<<<< HEAD
		54: "痛苦杂音",
		55: "音速缩放",
		56: "自动燃气",
		57: "别再想了",
		58: "多宇宙还在拓展",

		61: "乌鸦吉米的首秀",
		62: "加强版生命",
		63: "时骨无存",
		64: "加速无用",
		65: "杀一人为罪",
		66: "我还以为那很多的",
		67: "组成宇宙的原子宇宙。",
		68: "旧亚病毒",

		71: "无限魔鬼崇拜下的有序层次",
		72: "黑暗滋生",
		73: "真太多了",
		74: "真实冲击",
		75: "惟有空白",
		76: "它们也形成空间了？？！！",
		77: "为屑而生",
		78: "咻咻咻",

		81: "超越世界",
		82: "嘿呀呀呀呀呀！",
		83: "无穷无尽的爱",
		84: "毫无意义的自动化",
		85: "聪明的极限",
		86: "打破无限",
		87: "无念",
		88: "无限爱你哟",

		91: "加强版黑暗",
		92: "亡者宇宙",
		93: "真够您刷的……",
		94: "不，没什么特别的",
		95: "太亮了",
		96: "永远无关紧要",
		97: "一尘不染",
		98: "感受热度",

		101: "比至高神还强",
		102: "相当能刷",
		103: "生于黑暗",
		104: "罗马征服者",
		105: "毁坏的社会",
		106: "反自动化",
		107: "接招吧",
		108: "真正的创新",

		111: "您为什么还要尝试呢？",
		112: "宇之不存",
		113: "瘟疫爆发",
		114: "缩 放",
		115: "一棍糊脸",
		116: "立方无限",
		117: "亡者复生",
		118: "真正的挑战？",

		121: "为什么？！？？！？？？！？！？？",
		122: "脱轨",
		123: "进入下个世纪",
		124: "九点钟蓝调",
		125: "真是浪费时间……",
		126: "迅速修复",
		127: "虚假净化",
		128: "真实削弱",

		131: "多宇宙收缩",
		132: "阻止你又有什么意义？",
		133: "这很基本，亲爱的华生。",
		134: "不用用那些功能吗？",
		135: "再也不见",
		136: "多宇宙最速",
		137: "回到过去",
		138: "舰队见势不对退了",
		
		141: "乌有成真",
		142: "无尽的努力",
		143: "深海",
		144: "下一级别",
		145: "伟大纪元",
		146: "真实无限+",
		147: "最大的挫折",
		148: "不可能的任务",
		
		151: "比手指还小的无限",
		152: "无用的学说",
		153: "这是一颗树",
		154: "到底什么是强子？",
		155: "实质增长",
		156: "绝无可能",
		157: "基础原理",
		158: "仍在重复",
		
		161: "变回孩子",
		162: "完全无用的学说",
		163: "弦点击器",
		164: "只有这么多了",
		165: "这还有什么意义吗？",
		166: "真实暴胀",
		167: "多宇宙是怎么控制住您的力量的？",
		168: "只有一种泡沫",
		
		171: "给我变啊！",
		172: "一定过去多年了",
		173: "加无可加的泡沫",
		174: "多宇宙在即",
		175: "无柱自撑",
		176: "进入现实",
		177: "软上限什么也不是",
		178: "征服多宇宙",
	},
	descs: {
		11: "至少走了formatDistance(100)。",
		12: "进行级别重置。",
		13: "进行阶层重置。",
		14: "进行火箭重置。",
		15: "至少拥有showNum(1)火箭燃料。",
		16: "解锁自动化。",
		17: "解锁时间反演。",
		18: "进行全体坍缩重置。",

		21: "至少走了boolean(extreme,三十,五百)千米。",
		22: "到达级别boolean(extreme,六,八)。",
		23: "到达阶层showNum(3)。",
		24: "到达showNum(2)火箭。",
		25: "至少拥有showNum(2)火箭燃料。",
		26: "解锁级别机器人。",
		27: "到达showNum(1000)时间方盒。",
		28: "到达showNum(66)残骸。",

		31: "至少走了formatDistance(1e12)",
		32: "到达级别showNum(12)",
		33: "到达阶层showNum(4)",
		34: "到达showNum(10)火箭。",
		35: "至少拥有showNum(3)火箭燃料。",
		36: "解锁阶层机器人。",
		37: "购买showNum(5)个时间反演升级。",
		38: "到达所有showNum(12)个坍缩里程碑。",

		41: "至少走了formatDistance(3.086e17)。",
		42: "到达级别showNum(20)",
		43: "到达阶层showNum(5)。",
		44: "到达showNum(1e+5)火箭。",
		45: "至少拥有showNum(6)普通火箭燃料。",
		46: "到达showNum(5000)碎屑。",
		47: "购买showNum(10)个时间反演升级。",
		48: "到达showNum(1e+10)智慧。",

		51: "至少走了formatDistance(4.4e26)。",
		52: "到达showNum(1e+8)火箭。",
		53: "至少拥有showNum(10)普通火箭燃料。",
		54: "到达showNum(1e+7)时间方盒。",
		55: "时间速度超过showNum(1e+5)倍。",
		56: "解锁燃料机器人。",
		57: "到达showNum(9e15)时间方盒。",
		58: "至少走了formatDistance(9.768e+48)。",

		61: "解锁病原体。",
		62: "到达showNum(1e+6)生命精华。",
		63: "到达showNum(1e28)时间方盒。",
		64: "到达级别showNum(50)。",
		65: "到达showNum(5e+7)残骸。",
		66: "使燃料机器人的间隔小于等于formatTime(120)。",
		67: "到达formatDistance(4.4e106)。",
		68: "所有showNum(10)个病原体升级至少各升1级。",

		71: "解锁黑暗圆环。",
		72: "到达showNum(50)黑暗物质。",
		73: "到达formatDistance(4.4e166)。",
		74: "到达showNum(1e60)火箭。",
		75: "购买showNum(5)个黑暗核心。",
		76: "到达showNum(1e100)火箭。",
		77: "到达showNum(1e80)碎屑。",
		78: "到达showNum(75)普通火箭燃料。",

		81: "受到无限的认可。",
		82: "到达showNum(9000.1)知识。",
		83: "到达showNum(3)认可。",
		84: "燃料机器人的数量超过showNum(100)。",
		85: "到达showNum(1.79e308)智慧。",
		86: "到达formatDistance(4.4e1026)。",
		87: "到达showNum(25e9)知识。",
		88: "到达showNum(10)认可。",

		91: "黑暗流至少为showNum(8e3)倍。",
		92: "到达showNum(1e80)残骸。",
		93: "到达showNum(666)飞升能量。",
		94: "到达showNum(14)认可。",
		95: "购买过每种启迪。",
		96: "级别机器人的数量超过showNum(1e33)。",
		97: "不购买病原体升级的前提下，到达formatDistance(4.4e416)。",
		98: "不购买黑暗核心的前提下，到达formatDistance(4.4e786)。",

		101: "完成一个boolean(extreme,第一行的)竞技场挑战。",
		102: "每种启迪分别购买showNum(2)级。",
		103: "到达showNum(1e18)黑暗物质。",
		104: "完成三个boolean(extreme,第一行的)竞技场挑战。",
		105: "时间速度到达showNum(2.22e2222)倍。",
		106: "到达showNum(20)认可。",
		107: "完成六个boolean(extreme,第一行的)竞技场挑战。",
		108: "解锁速度能量。",

		111: "燃料机器人的间隔小于1秒。",
		112: "到达formatDistance(2.2e10022)/秒^2的加速度。",
		113: "到达showNum(250)%病原体升级效果。",
		114: "到达formatDistance(4.4e26)/秒^2加速能量。",
		115: "获得净化能量。",
		116: "到达showNum(25)认可。",
		117: "到达showNum(1e3000)残骸。",
		118: "在 永恒 竞技场挑战中，到达formatDistance(1e33600)。",

		121: "在难度6级的 现实 竞技场挑战中，到达formatDistance(2.5e4)。",
		122: "购买两次导数变换。",
		123: "到达showNum(2.5e5)飞升能量。",
		124: "到达boolean(extreme,九,十三)净化能量。",
		125: "在难度6级的 现实 竞技场挑战中，进行净化并到达formatDistance(1e4)。",
		126: "级别机器人的数量到达showNum(1e200)。",
		127: "不购买病原体升级和黑暗核心的前提下，到达showNum(1e100000)时间方盒。",
		128: "进行净化并到达formatDistance(5.55e5555)/秒^2的加速度。",

		131: "进行基本重置。",
		132: "在难度6级的 现实 竞技场挑战中，未在当前无限中购买无限8;8升级的前提下，进行净化并到达到达formatDistance(1e15)。",
		133: "到达showNum(1e3)费米子和玻色子。",
		134: "未在当前无限中购买病原体升级和黑暗核心的前提下，到达formatDistance(4.4e1100026)。",
		135: "到达showNum(2.5e7)天堂碎片。",
		136: "到达showNum(1e3750000)宇宙/秒的速度。",
		137: "不购买导数提升的前提下，进行基本重置(但您可以进行导数变换)。",
		138: "在认可不大于10的前提下，到达formatDistance(4.4e7826)。",
		
		141: "获得学说点数。",
		142: "在难度6级的 现实 竞技场挑战中，未在当前无限中购买病原体升级和黑暗核心的前提下，进行净化并到达formatDistance(4.4e136)。",
		143: "学说宇宙完成深度4。",
		144: "到达showNum(1e33)飞升能量。",
		145: "到达formatDistance(4.4e8000026)。",
		146: "到达showNum(1.8e308)知识。",
		147: "在认可不大于10的前提下，到达级别showNum(200)。",
		148: "到达级别showNum(995)。",
		
		151: "解锁强子挑战。",
		152: "至少获得showNum(2.3)强子分数。",
		153: "不购买任何学说树升级的前提下，到达formatDistance(4.4e8250026)。",
		154: "至少获得2.5强子分数并到达formatDistance(e2.8e7)，可以不同时完成。",
		155: "解锁暴胀子",
		156: "学说宇宙完成深度8。",
		157: "一维弦到达formatDistance(4.4e76)。",
		158: "至少获得showNum(3.75)强子分数。",
		
		161: "解锁量子泡沫。",
		162: "一维弦到达formatDistance(4.4e251)。",
		163: "纠缠弦到达formatDistance(4.4e126)。",
		164: "解锁熵。",
		165: "至少获得showNum(8)强子分数。",
		166: "到达boolean(extreme,showNup[1e150],showNup[1e160])暴胀子。",
		167: "到达showNum(1e108000000)宇宙。",
		168: "不购买亚普朗克泡沫的前提下，到达showNum(1e25)量子泡沫。",
		
		171: "获得斯格明子。",
		172: "基本重置showNum(1e12)次。",
		173: "没有任何熵的前提下，到达boolean(extreme,showNup[1e78],showNup[1e140])量子泡沫。",
		174: "到达formatDistance(4.4e500000026)。",
		175: "没有任何熵，且不购买亚普朗克泡沫，光子和胶子升级的前提下，到达formatDistance(4.4e222222248)。", 
		176: "学说宇宙完成深度19。",
		177: "至少获得showNum(1625)%病原体升级效果。",
		178: "到达formatDistance(4.4e1000000026)。",
	},
	rewards: {
		12: "加速度增加showNum(10)%boolean(extreme,，且每获得一个成就，级别降价器就增强0.5倍，效果叠加)。",
		14: "加速度和最大速度增加showNum(50)%boolean(extreme,，且火箭重置时您直接获得1个级别降价器)。",
		15: "火箭的获取量增加showNum(5)%boolean(extreme,，并解锁熔炉)。",
		16: "boolean(extreme+hikers_dream,根据动力总量，增加煤的获取量。)",
		17: "时间加快showNum(1)%。",
		18: "时间加快showNum(50)%。",

		21: "最大速度增加showNum(10)%boolean(extreme,，且每1个阶层您额外获得1个级别降价器)。",
		22: "加速度增加showNum(5)%boolean(extreme,，且阶层重置时您直接获得1个级别降价器)",
		23: "加速度增加showNum(20)%。",
		24: "最大速度增加showNum(25)%boolean(extreme,，且此列每解锁一个成就，加速度就变为2倍)。",
		26: "火箭的获取量增加showNum(10)%boolean(extreme+hikers_dream,，且 优化 升级以较低的倍率增加煤的获取量)。",
		27: "时间加快showNum(10)%。",

		32: "加速度增加showNum(80)%。",
		34: "火箭的获取量增加showNum(10)%boolean(extreme,，且您再次额外获得1个级别降价器)。",
		35: "加速度增加showNum(80)%boolean(extreme,，且煤的效果翻倍)。",
		36: "碎屑和智慧的获取量增加showNum(50)%boolean(extreme+hikers_dream,，且每个熔炉升级使 优化 升级软上限的起始值增加10%)。",
		38: "残骸的获取量翻倍boolean(extreme+hikers_dream,，且乘以能量升级总量的平方，最小为1)。",

		41: "最大速度增加showNum(50)%。",
		43: "级别需求公式缓和showNum(2.5)%。",
		44: "火箭的获取量增加showNum(15)%。",
		46: "智慧的获取量翻倍。",
		47: "时间加快showNum(50)%。",
		48: "您可以最大化购买机器人升级。",

		51: "最大速度增加showNum(50)%。",
		52: "时间加快showNum(20)%。",
		55: "时间方盒的获取量增加showNum(10)%。",
		57: "时间加快showNum(10)%。",
		58: "火箭燃料重置改为将火箭重置为当前数量的showNum(50)%。",

		61: "最大速度增加showNum(60)%boolean(extreme+hikers_dream,，且将能量损耗除以时间方盒升级总量，最小为1)。",
		63: "时间速度以较低的倍率增加病原体的获取量。",
		65: "残骸的获取量增加showNum(40)%boolean(extreme+hikers_dream,，每个病原体升级使 信心 升级软上限增加三分之一)boolean(hard,，且病原体升级软上限延迟5次出现)",
		66: "boolean(extreme+hikers_dream,加强 推进器 III 升级的效果，且根据煤数值，加强 优化 升级的效果。)",
		67: "时间加快showNum(11.11)%boolean(extreme+hikers_dream,，且 优化 升级软上限延迟5次出现， 信心 升级软上限延迟1次出现)。",
		68: "病原体的获取量变为showNum(2.5)倍boolean(hard+hikers_dream,，根据 信心 升级数值，增加病原体的获取量)boolean(extreme,，且残骸的获取量变为5倍)。",

		72: "不进行时间反演也可以获得时间方盒，但速度减半boolean(extreme,，且根据煤和黑暗核心数值，增加时间方盒的获取量)。",
		74: "'时骨无存'成就的奖励增加showNum(75)%。",
		75: "黑暗流加快showNum(10)%。",
		76: "火箭的获取量增加showNum(2)%",
		77: "boolean(extreme+hikers_dream,根据火箭数值，增加动力的基础软上限。)",

		81: "无限时保留自动化相关内容。",
		83: "黑暗流加快showNum(20)%。",
		84: "黑暗流影响病原体的获取量，在showNum(50)倍以后效果减少。",
		85: "boolean(hard+hikers_dream,您可以随时复原能量)boolean(extreme+hikers_dream,，且使 持久性 升级变为原来的平方)boolean(hard+hikers_dream,。)",
		86: "boolean(extreme+hikers_dream,使时间方盒的获取量变为病原体数值的倍数，并使 信心 升级软上限的起始值变为原来的平方。)",
		87: "boolean(extreme+hikers_dream,移除动力的基础软上限)boolean(hard+hikers_dream,，且根据时间方盒数值，加强病原体升级的效果。)",
		88: "购买病原体升级不再花费病原体boolean(extreme,，且解锁熔炉挑战)。",

		92: "购买黑暗核心不再减少残骸数值。",
		93: "boolean(extreme+hikers_dream,使 信心 升级软上限的起始值变为原来的平方。)",
		94: "boolean(hard-extreme,即使特权未激活也可以产生飞升能量。)",
		95: "每秒获得当前产量showNum(100)%的火箭。",
		96: "每秒获得当前产量showNum(100)%的残骸。",
		97: "每秒将showNum(100)%数值的残骸转化为生命精华boolean(extreme+hikers_dream,，且根据 优化 升级数值，增加 信心 升级软上限的起始值)。",

		102: "boolean(extreme+hikers_dream,将 信心 升级软上限的起始值变为认可数值的倍数。)",
		103: "可以多激活一个特权。",
		105: "加速度增加showNum(300)%boolean(extreme,，且级别机器人和阶层机器人的数量受间隔加成的效果变得更好)。",
		108: "知识的获取量增加showNum(50)%boolean(extreme,，且折算的认可延迟2次出现)。",

		111: "可以同时激活所有四个特权boolean(extreme,，且解锁强化熔炉)。",
		112: "根据时间速度数值，以较低的倍率增加知识的获取量boolean(extreme,，且级别降价器不再重置任何东西)。",
		116: "天堂碎片和恶魔灵魂的获取量翻倍boolean(extreme,，且进行净化时时间速度可以生效，每有1点净化能量，强化煤的获取量就增加40%)。",
		117: "boolean(extreme+hikers_dream,移除 信心 升级的软上限。)",

		123: "宇之不存成就的公式变得略好一些boolean(hard+hikers_dream,，且 信心 升级效果变为原来的10倍)。",
		124: "特权持续时间翻倍。",
		125: "病原体升级的效果增加showNum(5)%。",

		131: "火箭，残骸，病原体的获取量翻倍，黑暗流加快showNum(50)%boolean(extreme,，且煤和强化煤的获取量总是变为100倍)。",
		132: "规范作用力的效果翻倍。",
		133: "解锁自动基本重置。",
		135: "净化能量的效果减半。",
		
		141: "boolean(hikers_dream,您可以保留发生器，并自动购买它们。)",
		142: "自动购买的认可不再重置任何东西。",
		143: "boolean(extreme+hikers_dream,您可以使用Shift键+点击来最大化购买学说树升级，请注意用这个方式购买的升级比正常更便宜。)boolean(hikers_dream,被动能量的获取量变为一千万倍。)",
		144: "所有弦的获取量增加showNum(25)%。",
		145: "boolean(hikers_dream,根据级别数值，加强无限10;10升级的效果。)",
		147: "进行净化时可以获得残骸，但倍率极低，且病原体升级效果不再永远为0%。",
		
		152: "根据最高强子分数数值，使所有学说树升级变得更便宜。",
		153: "boolean(extreme+hikers_dream,能够使折算的认可延迟出现的学说树升级也对超级折算的认可生效，但效果较低，只有原来的十分之一)",
		154: "净化能量的获取量翻倍boolean(hikers_dream,，且解锁第27个和第28个能量升级)。",
		157: "所有弦的获取量翻倍。",
		
		162: "根据未花费的学说点数数值，使所有类型的泡沫效果变得更好boolean(extreme+hikers_dream,。,，您可以使用Shift键+点击来最大化购买学说树升级，请注意用这个方式购买的升级比正常更便宜。)",
		163: "每秒获得当前产量10%的纠缠弦。",
		166: "解锁自动光子升级和自动胶子升级。",
		168: "解锁自动学说树升级。",
		
		171: "拓展泡沫不再消耗它本身，量子泡沫的获取量变为10倍，亚普朗克泡沫的获取量变为20倍，子空间泡沫的获取量变为30倍，依此类推boolean(hikers_dream,，且解锁第29个和第30个能量升级)",
		172: "每三个数量级的基本重置可以使基本粒子获取量的软上限延迟showNum(20)%出现。",
		174: "特权加速器的效果增加showNum(5)%。",
=======
		54: "Cacophany of Pain",
		55: "Zooming at the Speed of Sound",
		56: "Auto-Gas",
		57: "No More Thinking",
		58: "The Multiverse is Ever-Expanding",

		61: "Jimmy the Crow's Debut",
		62: "Alive Plus",
		63: "Time Doesn't Exist",
		64: "Acceleration does nothing.",
		65: "One Death",
		66: "I thought that was a lot?",
		67: "Atoms in the universe, of universes.",
		68: "Corvid Twenty",

		71: "The Infinite Satanic Cult Of Orderly Layers",
		72: "Darkness Grows",
		73: "Too much for you",
		74: "True Blast",
		75: "Got nothin' but blank",
		76: "They have space too??!!",
		77: "Trash is life",
		78: "Pew Pew Pew",

		81: "Beyond the World of Normality",
		82: "HYAAAAA!",
		83: "Infinite Love",
		84: "Pointless Automation",
		85: "I is smort.",
		86: "Infinity is Broke",
		87: "No Thoughts",
		88: "Infinity Likes You",

		91: "Dark Plus",
		92: "Universe of Death",
		93: "Well that was a grind...",
		94: "No, it's not special",
		95: "Too Bright",
		96: "This'll never matter",
		97: "Clean as a Whistle",
		98: "Feel The Heat",

		101: "Stronger than a High God",
		102: "Kinda Grindy",
		103: "I Live In Darkness",
		104: "Roman Conqueror",
		105: "Ruined Society",
		106: "Anti-Automation",
		107: "You are challenged?",
		108: "True Innovation",

		111: "Why do you even try?",
		112: "The Universe Doesn't Exist",
		113: "Outbreak 76",
		114: "ZOOM",
		115: "Club to the face",
		116: "Cubic Infinity",
		117: "The Dead Have Risen",
		118: "The True Challenge?",

		121: "Why?!??!???!?!??",
		122: "Off the Rails",
		123: "Into the Next Century",
		124: "9 o'clock blues",
		125: "What a waste of time...",
		126: "Quick Repair",
		127: "False Purge",
		128: "Truly Nerfed",

		131: "Shrinking the Multiverse",
		132: "What's the point of even stopping you?",
		133: "It's Elementary, my dear Watson.",
		134: "Why use the features I give you?",
		135: "Never Seen Again",
		136: "Fastest in the Multiverse",
		137: "Back to the Past",
		138: "The Fleet Flees",

		141: "The Impossible Happened",
		142: "Endless Endeavours",
		143: "Under the C",
		144: "To The Next Rank",
		145: "The Great Epoch",
		146: "True Infinity+",
		147: "The Biggest Setback",
		148: "The Impossible Task",

		151: "An infinity smaller than your fingertip",
		152: "Useless Theories",
		153: "There is a tree",
		154: "What even are Hadrons?",
		155: "Real Growth",
		156: "IMPOSSIBLE",
		157: "The Principle of the Basics",
		158: "The Repetition Continues",

		161: "We're kids again",
		162: "Actually Useless Theories",
		163: "String Clickers",
		164: "There are only so many",
		165: "Is there even a point to these anymore?",
		166: "True Inflation",
		167: "How is the Multiverse containing your power?",
		168: "There is only one Fome",

		171: "TRANSFOOOOORM!",
		172: "This must have taken years",
		173: "Extensionless Fome",
		174: "The Multiverse is Doomed",
		175: "Removing the Pillars",
		176: "Entering Reality",
		177: "Softcaps mean NOTHING",
		178: "Multiverse Conquered",

		181: "Two In One Deal",
		182: "Multiverse of Madness",
		183: "Fermionic Embassy",
		184: "The Entropy Sublimit",
		185: "Eternal Torture",
		186: "King of the Damned",
		187: "Conquering the Megaverse",
		188: "Not So Proto Now?",

		191: "Vantablack Explosion",
		192: "The Leetest Titan",
		193: "Conqueror of the Lands",
		194: "Nice Beloved Quality",
		195: "Millionaire Multipreneur",
		196: "Hadron Manipulation",
		197: "Billionaire X",
		198: "Overlord of Everything",
	},
	descs: {
		11: "Go at least formatDistance(100).",
		12: "Do a rank reset.",
		13: "Do a tier reset.",
		14: "Do a rocket reset.",
		15: "Get at least showNum(1) rocket fuel.",
		16: "Unlock automation.",
		17: "Unlock Time Reversal.",
		18: "Perform a Universal Collapse reset.",

		21: "Go at least boolean(extreme,thirty,five hundred) km.",
		22: "Reach Rankboolean(extreme, six, eight).",
		23: "Reach Tier showNum(3).",
		24: "Reach showNum(2) Rockets.",
		25: "Get at least showNum(2) rocket fuel.",
		26: "Unlock Rankbot.",
		27: "Reach showNum(1000) Time Cubes.",
		28: "Reach showNum(66) Cadavers.",

		31: "Go at least formatDistance(1e12)",
		32: "Reach Rank showNum(12)",
		33: "Reach Tier showNum(4)",
		34: "Reach showNum(10) Rockets.",
		35: "Get at least showNum(3) rocket fuel.",
		36: "Unlock Tierbot.",
		37: "Purchase showNum(5) Time Reversal Upgrades.",
		38: "Reach all showNum(12) Collapse Milestones.",

		41: "Go at least formatDistance(3.086e17).",
		42: "Reach Rank showNum(20)",
		43: "Reach Tier showNum(5).",
		44: "Reach showNum(1e+5) Rockets.",
		45: "Get at least showNum(6) normal rocket fuel.",
		46: "Reach showNum(5000) scraps.",
		47: "Purchase showNum(10) Time Reversal Upgrades.",
		48: "Reach showNum(1e+10) intelligence.",

		51: "Go at least formatDistance(4.4e26).",
		52: "Reach showNum(1e+8) Rockets.",
		53: "Get at least showNum(10) normal rocket fuel.",
		54: "Reach showNum(1e+7) Time Cubes.",
		55: "Get a Time Speed above showNum(1e+5)x.",
		56: "Unlock Fuelbot.",
		57: "Reach showNum(9e15) Time Cubes.",
		58: "Go at least formatDistance(9.768e+48).",

		61: "Unlock Pathogens.",
		62: "Reach showNum(1e+6) Life Essence.",
		63: "Reach showNum(1e28) Time Cubes.",
		64: "Reach Rank showNum(50).",
		65: "Reach showNum(5e+7) Cadavers.",
		66: "Get Fuelbot's interval less than or equal to formatTime(120).",
		67: "Reach formatDistance(4.4e106).",
		68: "Get one of each of the showNum(10) Pathogen upgrades.",

		71: "Unlock The Dark Circle.",
		72: "Reach showNum(50) Dark Matter.",
		73: "Reach formatDistance(4.4e166).",
		74: "Reach showNum(1e60) Rockets.",
		75: "Purchase showNum(5) Dark Cores.",
		76: "Reach showNum(1e100) Rockets.",
		77: "Reach showNum(1e80) Scraps.",
		78: "Reach showNum(75) normal Rocket Fuel.",

		81: "Get endorsed by Infinity.",
		82: "Reach showNum(9000.1) knowledge.",
		83: "Reach showNum(3) endorsements.",
		84: "Have a magnitude above showNum(100) for Fuelbot.",
		85: "Reach showNum(1.79e308) intelligence.",
		86: "Reach formatDistance(4.4e1026).",
		87: "Reach showNum(25e9) knowledge.",
		88: "Reach showNum(10) Endorsements.",

		91: "Have a Dark Flow of at least showNum(8e3)x.",
		92: "Reach showNum(1e80) Cadavers.",
		93: "Reach showNum(666) Ascension Power.",
		94: "Reach showNum(14) Endorsements.",
		95: "Purchase one of each Enlightenment.",
		96: "Have a magnitude above showNum(1e33) for Rankbot.",
		97: "Reach formatDistance(4.4e416) without any Pathogen Upgrades.",
		98: "Reach formatDistance(4.4e786) without any Dark Cores.",

		101: "Complete oneboolean(extreme, first row) Stadium Challenge.",
		102: "Purchase showNum(2) of each Enlightenment.",
		103: "Reach showNum(1e18) Dark Matter.",
		104: "Complete threeboolean(extreme, first row) Stadium Challenges.",
		105: "Reach a Time Speed of showNum(2.22e2222)x.",
		106: "Reach showNum(20) Endorsements.",
		107: "Complete sixboolean(extreme, first row) Stadium Challenges.",
		108: "Unlock Velocital Energy.",

		111: "Have an interval below 1s for Fuelbot.",
		112: "Reach formatDistance(2.2e10022)/s^2 of acceleration.",
		113: "Reach showNum(250)% of Pathogen Upgrade power.",
		114: "Reach formatDistance(4.4e26)/s^2 of Accelerational Energy.",
		115: "Gain Purge Power.",
		116: "Reach showNum(25) Endorsements.",
		117: "Reach showNum(1e3000) Cadavers.",
		118: "Reach formatDistance(1e33600) while in Eternity's Stadium challenge.",

		121: "Reach formatDistance(2.5e4) while in Reality's Stadium challenge at Difficulty Level 6.",
		122: "Purchase two Derivative Shifts.",
		123: "Reach showNum(2.5e5) Ascension Power.",
		124: "Reach boolean(extreme,nine,thirty) Purge Power.",
		125: "Reach formatDistance(1e4) while in a Purge run & in Reality's Stadium challenge at Difficulty Level 6.",
		126: "Have a magnitude of boolean(hard,showNup[1e75],showNup[1e200]) for Rankbot.",
		127: "Reach showNum(1e100000) Time Cubes without any Pathogen Upgrades or Dark Cores.",
		128: "Reach formatDistance(5.55e5555)/s^2 of Acceleration while in a Purge run.",

		131: "Perform an Elementary reset.",
		132: "Reach formatDistance(1e15) while in a Purge run, without inf8;8 in the current Infinity, & while in Reality's Stadium challenge at Difficulty Level 6.",
		133: "Reach showNum(1e3) Fermions & Bosons.",
		134: "Reach formatDistance(4.4e1100026) without Pathogen Upgrades & Dark Cores in the current Infinity.",
		135: "Reach showNum(2.5e7) Heavenly Chips.",
		136: "Reach showNum(1e3750000) uni/s of Velocity.",
		137: "Do an Elementary reset without any Derivative Boosts (but you can have Derivative Shifts).",
		138: "Reach formatDistance(4.4e7826) while having ten Endorsements or less.",

		141: "Get a Theory Point.",
		142: "Reach formatDistance(4.4e136) while in a Purge run, while in Reality's Stadium challenge at Difficulty Level 6, and without Pathogen Upgrades & Dark Cores in the current Infinity.",
		143: "Complete The Theoriverse at Depth 4.",
		144: "Reach showNum(1e33) Ascension Power.",
		145: "Reach formatDistance(4.4e8000026).",
		146: "Reach showNum(1.8e308) Knowledge.",
		147: "Reach Rank showNum(200) with ten Endorsements or less.",
		148: "Reach Rank showNum(995).",

		151: "Unlock Hadronic Challenge.",
		152: "Get a Hadronic Score of at least showNum(2.3).",
		153: "Reach formatDistance(4.4e8250026) without any Theory Tree Upgrades.",
		154: "Get a Hadronic Score of at least 2.5 and reach formatDistance(e2.8e7), can be on separate runs.",
		155: "Unlock Inflatons",
		156: "Complete The Theoriverse at Depth 8.",
		157: "Reach formatDistance(4.4e76) of Primary String.",
		158: "Get a Hadronic Score of at least showNum(3.75).",

		161: "Unlock Quantum Foam.",
		162: "Reach formatDistance(4.4e251) of Primary String.",
		163: "Reach formatDistance(4.4e126) of Entangled String.",
		164: "Unlock Entropy.",
		165: "Get a Hadronic Score of at least showNum(8).",
		166: "Reach boolean(extreme,showNup[1e150],showNup[1e160]) Inflatons.",
		167: "Reach showNum(1e108000000) uni.",
		168: "Reach showNum(1e25) Quantum Foam without any Subplanck Foam.",

		171: "Get a Skyrmion.",
		172: "Elementary showNum(1e12) times.",
		173: "Reach boolean(extreme,showNup[1e78],showNup[1e140]) Quantum Foam without any Entropy.",
		174: "Reach formatDistance(4.4e500000026).",
		175: "Reach formatDistance(4.4e222222248) without any Entropy, Subplanck Foam, or Photon/Gluon Upgrades.",
		176: "Complete The Theoriverse at Depth 19.",
		177: "Have Pathogen Upgrade Power of at least showNum(1625)%.",
		178: "Reach formatDistance(4.4e1000000026).",

		181: "Reach formatDistance(1.936e2000000053).",
		182: "Reach formatDistance(1.7868e3500000093) without any Theoriverse completions.",
		183: "Complete Multiverse 1.",
		184: "Reach showNum(1e5) Entropy.",
		185: "Reach formatDistance(3.911111e88888915) while in Multiverse 2 and Eternity's Stadium challenge at Difficulty Level 6.",
		186: "Reach formatDistance(2.21e100000002664).",
		187: "Complete Multiverse 5.",
		188: "Reach showNum(1e430) Protoversal Foam.",

		191: "Purchase showNum(10) Dark Expanders.",
		192: "Get showNum(1337) Ranks in Multiverse 1 without unlocking Theories, Hadronic Challenge, Foam, or Skyrmions.",
		193: "Reach formatDistance(4.4e800000026) in Multiverse 3 without unlocking Ascension.",
		194: "Reach Tier showNum(69).",
		195: "Gain showNum(1e6) Multiversal Energy in one reset.",
		196: "Reach formatDistance(4.4e10000026) in Multiverse 5 while in a Hadronic Challenge with a Projected Score of at least boolean(extreme,12,15).",
		197: "Gain showNum(1e9) Multiversal Energy in one reset.",
		198: "Reach formatDistance(2.8e1000000026643).",
	},
	rewards: {
		12: "Acceleration is showNum(10)% higherboolean(extreme, and Rank Cheapeners are +0.5x stronger for each achievement gotten).",
		14: "Acceleration & Maximum Velocity are showNum(50)% higherboolean(extreme, and you start with one Rank Cheapener on Rocket reset).",
		15: "Rocket gain is increased by showNum(5)%boolean(extreme, and unlock The Furnace).",
		16: "boolean(extreme+hikers_dream,Total motive boosts coal gain.)",
		17: "Time goes by showNum(1)% faster.",
		18: "Time goes by showNum(50)% faster.",

		21: "Maximum Velocity is showNum(10)% higherboolean(extreme, and you get one extra Rank Cheapener for every Tier).",
		22: "Acceleration is showNum(5)% higherboolean(extreme, and you start with one Rank Cheapener on Tier reset)",
		23: "Acceleration is showNum(20)% higher.",
		24: "Maximum Velocity is showNum(25)% higherboolean(extreme, and acceleration is twice as fast for each achievement unlocked in this column).",
		26: "Rocket gain is increased by showNum(10)%boolean(extreme+hikers_dream, and Optimization boosts coal gain at reduced rate).",
		27: "Time goes by showNum(10)% faster.",

		32: "Acceleration is showNum(80)% higher.",
		34: "Rocket gain is increased by showNum(10)%boolean(extreme, and you get another extra Rank Cheapener).",
		35: "Acceleration is showNum(80)% higherboolean(extreme, and the Coal effect is doubled).",
		36: "Scrap & intelligence gain are increased by showNum(50)%boolean(extreme+hikers_dream, and each furnace upgrade increase the Optimization softcap start by 10%).",
		38: "Cadaver gain is doubledboolean(extreme+hikers_dream, and multiplied by the square of energy upgrades (minimum 1)).",

		41: "Maximum Velocity is showNum(50)% higher.",
		43: "The Rank requirement formula is showNum(2.5)% slower.",
		44: "Rocket gain is increased by showNum(15)%.",
		46: "Intelligence gain is doubled.",
		47: "Time goes by showNum(50)% faster.",
		48: "You can buy max robot upgrades.",

		51: "Maximum Velocity is showNum(50)% higher.",
		52: "Time goes by showNum(20)% faster.",
		55: "You gain showNum(10)% more Time Cubes.",
		57: "Time goes by showNum(10)% faster.",
		58: "The Rocket Fuel reset only resets Rockets to showNum(50)% of their current amount.",

		61: "Maximum Velocity is showNum(60)% higherboolean(extreme+hikers_dream, and divide energy loss by time cube upgrades (minimum 1)).",
		63: "Time Speed boosts Pathogen gain at a reduced rate.",
		65: "Cadaver gain is increased by showNum(40)%boolean(extreme+hikers_dream, increase the Confidence softcap by one third per Pathogen upgrade)boolean(hard, and Pathogen Upgrades softcap five later)",
		66: "boolean(extreme+hikers_dream,Buff Thrusters III and Coal boosts Optimization.)",
		67: "Time goes by showNum(11.11)% fasterboolean(extreme+hikers_dream, increase the Optimization softcap by 5 times and increase the Confidence softcap by 1).",
		68: "Pathogen gain is showNum(2.5)x fasterboolean(hard+hikers_dream, Confidence boosts Pathogen gain)boolean(extreme, and Cadaver gain is quintupled).",

		72: "You gain Time Cubes without Reversing Time, however only at half the rateboolean(extreme, and Time Cube gain is faster based on your Coal & Dark Cores).",
		74: "The 'Time Doesnt Exist' reward is showNum(75)% stronger.",
		75: "Dark Flow is showNum(10)% faster.",
		76: "Rocket gain is increased by showNum(2)%",
		77: "boolean(extreme+hikers_dream,Increase the base motivation softcap based on rockets.)",

		81: "Keep automation stuff on Infinity.",
		83: "Dark Flow is showNum(20)% faster.",
		84: "Dark Flow affects Pathogen gain, slows down after showNum(50)x.",
		85: "boolean(hard+hikers_dream,You can rejuvinate whenever)boolean(extreme+hikers_dream, and square Endurance)boolean(hard+hikers_dream,.)",
		86: "boolean(extreme+hikers_dream,Pathogens multiply time cube gain and square Confidence softcap start.)",
		87: "boolean(extreme+hikers_dream,Remove the base motivation softcap)boolean(hard+hikers_dream, and time cubes boost pathogens.)",
		88: "Buying Pathogen Upgrades does not spend your Pathogensboolean(extreme, and you unlock Furnace Challenges).",

		92: "When buying Dark Cores, your Cadavers do not decrease.",
		93: "boolean(extreme+hikers_dream,Square Confidence softcap start.)",
		94: "boolean(hard-extreme,Generate Ascension Power even if perks are inactive.)",
		95: "Gain showNum(100)% of Rocket gain every second.",
		96: "Gain showNum(100)% of Cadaver gain every second.",
		97: "Transfer showNum(100)% of Cadavers to Life Essence every secondboolean(extreme+hikers_dream, and Optimization increases Confidence softcap start).",

		102: "boolean(extreme+hikers_dream,Endorsements multiply Confidence softcap start.)",
		103: "You can activate one extra perk at any given time.",
		105: "Acceleration is showNum(300)% fasterboolean(extreme, and Rankbot & Tierbot's magnitudes are boosted by their intervals even more).",
		108: "Knowledge gain is showNum(50)% fasterboolean(extreme, and Scaled Endorsement scaling starts 2 Endorsements later).",

		111: "You can activate all four perks at onceboolean(extreme, and unlock the Enhanced Furnace).",
		112: "Time Speed boosts Knowledge gain at a reduced rateboolean(extreme, and Rank Cheapeners do not reset anything).",
		116: "You gain twice as many Heavenly Chips & Demonic Soulsboolean(extreme, and Time Speed is enabled in Purge runs and Enhanced Coal gain is 40% faster for each Purge Power you have).",
		117: "boolean(extreme+hikers_dream,Remove the Confidence softcap.)",

		123: "The Universe Doesn't Exist achievement uses a slightly better formulaboolean(hard+hikers_dream, and Confidence is ten times stronger).",
		124: "All Perks last twice as long.",
		125: "Pathogen Upgrades are showNum(5)% stronger.",

		131: "Rockets, Cadavers, & Pathogens are gained twice as fast, and Dark Flow is showNum(50)% fasterboolean(extreme, and coal & enhanced coal gain is always 100x faster).",
		132: "The Gauge Force Effect is doubled.",
		133: "Unlock Auto-Elementaries.",
		135: "The Purge Power effect is halved.",

		141: "boolean(hikers_dream,Keep generators and buy them automatically.)",
		142: "Endorsements that are bought automatically do not reset anything.",
		143: "boolean(extreme+hikers_dream,You can buy max Theory Tree Upgrades with shift+click which is slightly more efficient than normally upgrading. )boolean(hikers_dream,Gain ten million times the passive energy.)",
		144: "All Strings are gained showNum(25)% faster.",
		145: "boolean(hikers_dream,inf10;10 is stronged based on your ranks.)",
		147: "You gain Cadavers while in Purge runs, but at a very reduced rate, and Pathogen Upgrades are not stuck at 0% power in Purge runs.",

		152: "All Theory Tree Upgrades are cheaper based on your Best Hadronic Score.",
		153: "boolean(extreme+hikers_dream,The Theory Tree Upgrade that makes Scaled Endorsements start later also makes Superscaled Endorsements start later at a reduced rate [x/10])",
		154: "Purge Power gain is doubledboolean(hikers_dream, and unlock a 27th & 28th energy upgrade).",
		157: "All Strings are gained twice as fast.",

		162: "Unspent Theory Points boost all Foam typesboolean(extreme+hikers_dream,., and you can buy max Theory Tree Upgrades with shift+click which is slightly more efficient than normally upgrading.)",
		163: "Gain 10% of your Entangled String gain every second.",
		166: "Unlock Auto-Photon Upgrades & Auto-Gluon Upgrades.",
		168: "Unlock Auto-Theory Tree Upgrades.",

		171: "Expanding your Foam does not spend it, and Quantum Foam is gained 10x faster, Subplanck Foam is gained 20x faster, Subspatial Foam is gained 30x faster, etc.boolean(hikers_dream, and unlock a 29th & 30th energy upgrade)",
		172: "The Elementary Particle gain softcap is showNum(20)% weaker for every three OoMs of Elementaries done.",
		174: "The Perk Accelerator is showNum(5)% stronger.",
		178: 'The Infinity popup is permanently disabled if you have Auto-Endorsements unlocked, unlock the "Max Pion & Spinor Fields" buttonboolean(extreme, and the Plasma exponent is doubled when below 250).',

		183: "All Entropy Upgrades are always unlocked.",
		185: "Hyper Pathogen Upgrade scaling is showNum(10)% weakerboolean(extreme, and gain twenty percent more Multiversal Energy).",
		186: "Unlock Auto-Multiverse Runs.",
		188: "Gain showNum(10)% more Entropy.",

		191: "boolean(extreme,White Flame is gained 5x faster.)",
		193: "Gain showNum(5)% more Multiversal Energyboolean(hikers_dream-extreme, and 10% more Entropy).",
		194: "Tier scaling is 0.69% weaker.",
		195: "Gain showNum(11)% more Entropy.",
		196: "boolean(extreme+hikers_dream,Useless Theories is boosted by Multiverse Quilt 3's 2nd effect)",
		197: "Entropy Upgrades are showNum(5)% cheaperboolean(hikers_dream-extreme, and Thrusters V is 12.5% stronger).",
		198: "Unlock new Hadronic Challenge Selectors, you can extend the Hadronic Challenge goal to your best-ever Distance, and you can extend the HC Theoriverse selector to your best-ever Theoriverse completed (capped at depth 100).",
>>>>>>> en-master
	}
};
