const ACH_DATA = {
	rows: 17,
	cols: 8,
	names: {
		11: "快速冲刺",
		12: "更好的鞋子",
		13: "魔鬼训练",
		14: "飞向太空！",
		15: "火箭冲击",
		16: "与人无关",
		17: "但您还是在前进。",
		18: "蓄意谋杀",

		21: "长途驾驶",
		22: "该换油了",
		23: "3是幸运数字",
		24: "又升空了？",
		25: "补充燃料",
		26: "自动化进化",
		27: "时者生存",
		28: "残骸如山",

		31: "土星公转",
		32: "加入假燃料",
		33: "IV测试",
		34: "既可十飞，何故单飞？",
		35: "三倍燃料",
		36: "自动化能量提升",
		37: "有这么多吗？",
		38: "心会很痛",

		41: "十秒视差",
		42: "狂风怒号",
		43: "就好这口",
		44: "这有意义吗？",
		45: "九千未满……",
		46: "磁铁的作用",
		47: "我全都要！",
		48: "超级聪明",

		51: "超凡脱俗",
		52: "滥箭充数",
		53: "2+2=10",
		54: "痛苦杂音",
		55: "音速缩放",
		56: "自动燃气",
		57: "别再想了",
		58: "多宇宙还在拓展",

		61: "乌鸦吉米的首秀",
		62: "加强版生命",
		63: "时骨无存",
		64: "加速无用",
		65: "杀一人为罪",
		66: "我还以为那很多的",
		67: "组成宇宙的原子宇宙。",
		68: "旧亚病毒",

		71: "无限魔鬼崇拜下的有序层次",
		72: "黑暗滋生",
		73: "真太多了",
		74: "真实冲击",
		75: "惟有空白",
		76: "它们也形成空间了？？！！",
		77: "为屑而生",
		78: "咻咻咻",

		81: "超越世界",
		82: "嘿呀呀呀呀呀！",
		83: "无穷无尽的爱",
		84: "毫无意义的自动化",
		85: "聪明的极限",
		86: "打破无限",
		87: "无念",
		88: "无限爱你哟",

		91: "加强版黑暗",
		92: "亡者宇宙",
		93: "真够您刷的……",
		94: "不，没什么特别的",
		95: "太亮了",
		96: "永远无关紧要",
		97: "一尘不染",
		98: "感受热度",

		101: "比至高神还强",
		102: "相当能刷",
		103: "生于黑暗",
		104: "罗马征服者",
		105: "毁坏的社会",
		106: "反自动化",
		107: "接招吧",
		108: "真正的创新",

		111: "您为什么还要尝试呢？",
		112: "宇之不存",
		113: "瘟疫爆发",
		114: "缩 放",
		115: "一棍糊脸",
		116: "立方无限",
		117: "亡者复生",
		118: "真正的挑战？",

		121: "为什么？！？？！？？？！？！？？",
		122: "脱轨",
		123: "进入下个世纪",
		124: "九点钟蓝调",
		125: "真是浪费时间……",
		126: "迅速修复",
		127: "虚假净化",
		128: "真实削弱",

		131: "多宇宙收缩",
		132: "阻止你的意义是什么？",
		133: "这很基本，亲爱的华生。",
		134: "不用用那些功能吗？",
		135: "再也不见",
		136: "多宇宙最速",
		137: "回到过去",
		138: "舰队见势不对退了",
		
		141: "乌有成真",
		142: "无尽的努力",
		143: "深海",
		144: "下一级别",
		145: "伟大纪元",
		146: "真实无限+",
		147: "最大的挫折",
		148: "不可能的任务",
		
		151: "比手指还小的无限",
		152: "无用的学说",
		153: "这是一颗树",
		154: "到底什么是强子？",
		155: "实质增长",
		156: "绝无可能",
		157: "基础原理",
		158: "仍在重复",
		
		161: "变回孩子",
		162: "完全无用的学说",
		163: "弦点击器",
		164: "只有这么多了",
		165: "这还有什么意义吗？",
		166: "真实暴胀",
		167: "多宇宙是怎么控制住您的力量的？",
		168: "只有一种泡沫",
		
		171: "给我变啊！",
		172: "一定过去多年了",
		173: "加无可加的泡沫",
		174: "多宇宙已注定",
		175: "无柱自撑",
		176: "进入现实",
		177: "软上限什么也不是",
		178: "征服多宇宙",
	},
	descs: {
		11: "至少走了formatDistance(100)。",
		12: "进行级别重置。",
		13: "进行阶层重置。",
		14: "进行火箭重置。",
		15: "至少拥有showNum(1)点火箭燃料。",
		16: "解锁自动化。",
		17: "解锁时间反演。",
		18: "进行全体坍缩重置。",

		21: "至少走了boolean(extreme,三十,五百)千米。",
		22: "到达级别boolean(extreme,六,八)。",
		23: "到达阶层showNum(3)。",
		24: "到达showNum(2)个火箭。",
		25: "至少拥有showNum(2)点火箭燃料。",
		26: "解锁级别机器人。",
		27: "到达showNum(1000)时间方盒。",
		28: "到达showNum(66)残骸。",

		31: "至少走了formatDistance(1e12)",
		32: "到达级别showNum(12)",
		33: "到达阶层showNum(4)",
		34: "到达showNum(10)个火箭。",
		35: "至少拥有showNum(3)点火箭燃料。",
		36: "解锁阶层机器人。",
		37: "购买showNum(5)个时间反演升级。",
		38: "到达所有showNum(12)个坍缩里程碑。",

		41: "至少走了formatDistance(3.086e17)。",
		42: "到达级别showNum(20)",
		43: "到达阶层showNum(5)。",
		44: "到达showNum(1e+5)个火箭。",
		45: "至少拥有showNum(6)点普通火箭燃料。",
		46: "到达showNum(5000)碎屑。",
		47: "购买showNum(10)个时间反演升级。",
		48: "到达showNum(1e+10)智慧。",

		51: "Go at least formatDistance(4.4e26).",
		52: "Reach showNum(1e+8) Rockets.",
		53: "Get at least showNum(10) normal rocket fuel.",
		54: "Reach showNum(1e+7) Time Cubes.",
		55: "Get a Time Speed above showNum(1e+5)x.",
		56: "Unlock Fuelbot.",
		57: "Reach showNum(9e15) Time Cubes.",
		58: "Go at least formatDistance(9.768e+48).",

		61: "Unlock Pathogens.",
		62: "Reach showNum(1e+6) Life Essence.",
		63: "Reach showNum(1e28) Time Cubes.",
		64: "Reach Rank showNum(50).",
		65: "Reach showNum(5e+7) Cadavers.",
		66: "Get Fuelbot's interval less than or equal to formatTime(120).",
		67: "Reach formatDistance(4.4e106).",
		68: "Get one of each of the showNum(10) Pathogen upgrades.",

		71: "Unlock The Dark Circle.",
		72: "Reach showNum(50) Dark Matter.",
		73: "Reach formatDistance(4.4e166).",
		74: "Reach showNum(1e60) Rockets.",
		75: "Purchase showNum(5) Dark Cores.",
		76: "Reach showNum(1e100) Rockets.",
		77: "Reach showNum(1e80) Scraps.",
		78: "Reach showNum(75) normal Rocket Fuel.",

		81: "Get endorsed by Infinity.",
		82: "Reach showNum(9000.1) knowledge.",
		83: "Reach showNum(3) endorsements.",
		84: "Have a magnitude above showNum(100) for Fuelbot.",
		85: "Reach showNum(1.79e308) intelligence.",
		86: "Reach formatDistance(4.4e1026).",
		87: "Reach showNum(25e9) knowledge.",
		88: "Reach showNum(10) Endorsements.",

		91: "Have a Dark Flow of at least showNum(8e3)x.",
		92: "Reach showNum(1e80) Cadavers.",
		93: "Reach showNum(666) Ascension Power.",
		94: "Reach showNum(14) Endorsements.",
		95: "Purchase one of each Enlightenment.",
		96: "Have a magnitude above showNum(1e33) for Rankbot.",
		97: "Reach formatDistance(4.4e416) without any Pathogen Upgrades.",
		98: "Reach formatDistance(4.4e786) without any Dark Cores.",

		101: "Complete oneboolean(extreme, first row) Stadium Challenge.",
		102: "Purchase showNum(2) of each Enlightenment.",
		103: "Reach showNum(1e18) Dark Matter.",
		104: "Complete threeboolean(extreme, first row) Stadium Challenges.",
		105: "Reach a Time Speed of showNum(2.22e2222)x.",
		106: "Reach showNum(20) Endorsements.",
		107: "Complete sixboolean(extreme, first row) Stadium Challenges.",
		108: "Unlock Velocital Energy.",

		111: "Have an interval below 1s for Fuelbot.",
		112: "Reach formatDistance(2.2e10022)/s^2 of acceleration.",
		113: "Reach showNum(250)% of Pathogen Upgrade power.",
		114: "Reach formatDistance(4.4e26)/s^2 of Accelerational Energy.",
		115: "Gain Purge Power.",
		116: "Reach showNum(25) Endorsements.",
		117: "Reach showNum(1e3000) Cadavers.",
		118: "Reach formatDistance(1e33600) while in Eternity's Stadium challenge.",

		121: "Reach formatDistance(2.5e4) while in Reality's Stadium challenge at Difficulty Level 6.",
		122: "Purchase two Derivative Shifts.",
		123: "Reach showNum(2.5e5) Ascension Power.",
		124: "Reach boolean(extreme,nine,thirty) Purge Power.",
		125: "Reach formatDistance(1e4) while in a Purge run & in Reality's Stadium challenge at Difficulty Level 6.",
		126: "Have a magnitude of showNum(1e200) for Rankbot.",
		127: "Reach showNum(1e100000) Time Cubes without any Pathogen Upgrades or Dark Cores.",
		128: "Reach formatDistance(5.55e5555)/s^2 of Acceleration while in a Purge run.",

		131: "Perform an Elementary reset.",
		132: "Reach formatDistance(1e15) while in a Purge run, without inf8;8 in the current Infinity, & while in Reality's Stadium challenge at Difficulty Level 6.",
		133: "Reach showNum(1e3) Fermions & Bosons.",
		134: "Reach formatDistance(4.4e1100026) without Pathogen Upgrades & Dark Cores in the current Infinity.",
		135: "Reach showNum(2.5e7) Heavenly Chips.",
		136: "Reach showNum(1e3750000) uni/s of Velocity.",
		137: "Do an Elementary reset without any Derivative Boosts (but you can have Derivative Shifts).",
		138: "Reach formatDistance(4.4e7826) while having ten Endorsements or less.",
		
		141: "Get a Theory Point.",
		142: "Reach formatDistance(4.4e136) while in a Purge run, while in Reality's Stadium challenge at Difficulty Level 6, and without Pathogen Upgrades & Dark Cores in the current Infinity.",
		143: "Complete The Theoriverse at Depth 4.",
		144: "Reach showNum(1e33) Ascension Power.",
		145: "Reach formatDistance(4.4e8000026).",
		146: "Reach showNum(1.8e308) Knowledge.",
		147: "Reach Rank showNum(200) with ten Endorsements or less.",
		148: "Reach Rank showNum(995).",
		
		151: "Unlock Hadronic Challenge.",
		152: "Get a Hadronic Score of at least showNum(2.3).",
		153: "Reach formatDistance(4.4e8250026) without any Theory Tree Upgrades.",
		154: "Get a Hadronic Score of at least 2.5 and reach formatDistance(e2.8e7), can be on separate runs.",
		155: "Unlock Inflatons",
		156: "Complete The Theoriverse at Depth 8.",
		157: "Reach formatDistance(4.4e76) of Primary String.",
		158: "Get a Hadronic Score of at least showNum(3.75).",
		
		161: "Unlock Quantum Foam.",
		162: "Reach formatDistance(4.4e251) of Primary String.",
		163: "Reach formatDistance(4.4e126) of Entangled String.",
		164: "Unlock Entropy.",
		165: "Get a Hadronic Score of at least showNum(8).",
		166: "Reach boolean(extreme,showNup[1e150],showNup[1e160]) Inflatons.",
		167: "Reach showNum(1e108000000) uni.",
		168: "Reach showNum(1e25) Quantum Foam without any Subplanck Foam.",
		
		171: "Get a Skyrmion.",
		172: "Elementary showNum(1e12) times.",
		173: "Reach boolean(extreme,showNup[1e78],showNup[1e140]) Quantum Foam without any Entropy.",
		174: "Reach formatDistance(4.4e500000026).",
		175: "Reach formatDistance(4.4e222222248) without any Entropy, Subplanck Foam, or Photon/Gluon Upgrades.", 
		176: "Complete The Theoriverse at Depth 19.",
		177: "Have Pathogen Upgrade Power of at least showNum(1625)%.",
		178: "Reach formatDistance(4.4e1000000026).",
	},
	rewards: {
		12: "Acceleration is showNum(10)% higherboolean(extreme, and Rank Cheapeners are +0.5x stronger for each achievement gotten).",
		14: "Acceleration & Maximum Velocity are showNum(50)% higherboolean(extreme, and you start with one Rank Cheapener on Rocket reset).",
		15: "Rocket gain is increased by showNum(5)%boolean(extreme, and unlock The Furnace).",
		16: "boolean(extreme+hikers_dream,Total motive boosts coal gain.)",
		17: "Time goes by showNum(1)% faster.",
		18: "Time goes by showNum(50)% faster.",

		21: "Maximum Velocity is showNum(10)% higherboolean(extreme, and you get one extra Rank Cheapener for every Tier).",
		22: "Acceleration is showNum(5)% higherboolean(extreme, and you start with one Rank Cheapener on Tier reset)",
		23: "Acceleration is showNum(20)% higher.",
		24: "Maximum Velocity is showNum(25)% higherboolean(extreme, and acceleration is twice as fast for each achievement unlocked in this column).",
		26: "Rocket gain is increased by showNum(10)%boolean(extreme+hikers_dream, and Optimization boosts coal gain at reduced rate).",
		27: "Time goes by showNum(10)% faster.",

		32: "Acceleration is showNum(80)% higher.",
		34: "Rocket gain is increased by showNum(10)%boolean(extreme, and you get another extra Rank Cheapener).",
		35: "Acceleration is showNum(80)% higherboolean(extreme, and the Coal effect is doubled).",
		36: "Scrap & intelligence gain are increased by showNum(50)%boolean(extreme+hikers_dream, and each furnace upgrade increase the Optimization softcap start by 10%).",
		38: "Cadaver gain is doubledboolean(extreme+hikers_dream, and multiplied by the square of energy upgrades (minimum 1)).",

		41: "Maximum Velocity is showNum(50)% higher.",
		43: "The Rank requirement formula is showNum(2.5)% slower.",
		44: "Rocket gain is increased by showNum(15)%.",
		46: "Intelligence gain is doubled.",
		47: "Time goes by showNum(50)% faster.",
		48: "You can buy max robot upgrades.",

		51: "Maximum Velocity is showNum(50)% higher.",
		52: "Time goes by showNum(20)% faster.",
		55: "You gain showNum(10)% more Time Cubes.",
		57: "Time goes by showNum(10)% faster.",
		58: "The Rocket Fuel reset only resets Rockets to showNum(50)% of their current amount.",

		61: "Maximum Velocity is showNum(60)% higherboolean(extreme+hikers_dream, and divide energy loss by time cube upgrades (minimum 1)).",
		63: "Time Speed boosts Pathogen gain at a reduced rate.",
		65: "Cadaver gain is increased by showNum(40)%boolean(extreme+hikers_dream, increase the Confidence softcap by one third per Pathogen upgrade)boolean(hard, and Pathogen Upgrades softcap five later)",
		66: "boolean(extreme+hikers_dream,Buff Thrusters III and Coal boosts Optimization.)",
		67: "Time goes by showNum(11.11)% fasterboolean(extreme+hikers_dream, increase the Optimization softcap by 5 times and increase the Confidence softcap by 1).",
		68: "Pathogen gain is showNum(2.5)x fasterboolean(hard+hikers_dream, Confidence boosts Pathogen gain)boolean(extreme, and Cadaver gain is quintupled).",

		72: "You gain Time Cubes without Reversing Time, however only at half the rateboolean(extreme, and Time Cube gain is faster based on your Coal & Dark Cores).",
		74: "The '时骨无存' reward is showNum(75)% stronger.",
		75: "Dark Flow is showNum(10)% faster.",
		76: "Rocket gain is increased by showNum(2)%",
		77: "boolean(extreme+hikers_dream,Increase the base motivation softcap based on rockets.)",

		81: "Keep automation stuff on Infinity.",
		83: "Dark Flow is showNum(20)% faster.",
		84: "Dark Flow affects Pathogen gain, slows down after showNum(50)x.",
		85: "boolean(hard+hikers_dream,You can rejuvinate whenever)boolean(extreme+hikers_dream, and square Endurance)boolean(hard+hikers_dream,.)",
		86: "boolean(extreme+hikers_dream,Pathogens multiply time cube gain and square Confidence softcap start.)",
		87: "boolean(extreme+hikers_dream,Remove the base motivation softcap)boolean(hard+hikers_dream, and time cubes boost pathogens.)",
		88: "Buying Pathogen Upgrades does not spend your Pathogensboolean(extreme, and you unlock Furnace Challenges).",

		92: "When buying Dark Cores, your Cadavers do not decrease.",
		93: "boolean(extreme+hikers_dream,Square Confidence softcap start.)",
		94: "boolean(hard-extreme,Generate Ascension Power even if perks are inactive.)",
		95: "Gain showNum(100)% of Rocket gain every second.",
		96: "Gain showNum(100)% of Cadaver gain every second.",
		97: "Transfer showNum(100)% of Cadavers to Life Essence every secondboolean(extreme+hikers_dream, and Optimization increases Confidence softcap start).",

		102: "boolean(extreme+hikers_dream,Endorsements multiply Confidence softcap start.)",
		103: "You can activate one extra perk at any given time.",
		105: "Acceleration is showNum(300)% fasterboolean(extreme, and Rankbot & Tierbot's magnitudes are boosted by their intervals even more).",
		108: "Knowledge gain is showNum(50)% fasterboolean(extreme, and Scaled Endorsement scaling starts 2 Endorsements later).",

		111: "You can activate all four perks at onceboolean(extreme, and unlock the Enhanced Furnace).",
		112: "Time Speed boosts Knowledge gain at a reduced rateboolean(extreme, and Rank Cheapeners do not reset anything).",
		116: "You gain twice as many Heavenly Chips & Demonic Soulsboolean(extreme, and Time Speed is enabled in Purge runs and Enhanced Coal gain is 40% faster for each Purge Power you have).",
		117: "boolean(extreme+hikers_dream,Remove the Confidence softcap.)",

		123: "宇之不存 achievement uses a slightly better formulaboolean(hard+hikers_dream, and Confidence is ten times stronger).",
		124: "All Perks last twice as long.",
		125: "Pathogen Upgrades are showNum(5)% stronger.",

		131: "Rockets, Cadavers, & Pathogens are gained twice as fast, and Dark Flow is showNum(50)% fasterboolean(extreme, and coal & enhanced coal gain is always 100x faster).",
		132: "The Gauge Force Effect is doubled.",
		133: "Unlock Auto-Elementaries.",
		135: "The Purge Power effect is halved.",
		
		141: "boolean(hikers_dream,Keep generators and buy them automatically.)",
		142: "Endorsements that are bought automatically do not reset anything.",
		143: "boolean(extreme+hikers_dream,You can buy max Theory Tree Upgrades with shift+click which is slightly more efficient than normally upgrading. )boolean(hikers_dream,Gain ten million times the passive energy.)",
		144: "All Strings are gained showNum(25)% faster.",
		145: "boolean(hikers_dream,inf10;10 is stronged based on your ranks.)",
		147: "You gain Cadavers while in Purge runs, but at a very reduced rate, and Pathogen Upgrades are not stuck at 0% power in Purge runs.",
		
		152: "All Theory Tree Upgrades are cheaper based on your Best Hadronic Score.",
		153: "boolean(extreme+hikers_dream,The Theory Tree Upgrade that makes Scaled Endorsements start later also makes Superscaled Endorsements start later at a reduced rate [x/10])",
		154: "Purge Power gain is doubledboolean(hikers_dream, and unlock a 27th & 28th energy upgrade).",
		157: "All Strings are gained twice as fast.",
		
		162: "Unspent Theory Points boost all Foam typesboolean(extreme+hikers_dream,., and you can buy max Theory Tree Upgrades with shift+click which is slightly more efficient than normally upgrading.)",
		163: "Gain 10% of your Entangled String gain every second.",
		166: "Unlock Auto-Photon Upgrades & Auto-Gluon Upgrades.",
		168: "Unlock Auto-Theory Tree Upgrades.",
		
		171: "Expanding your Foam does not spend it, and Quantum Foam is gained 10x faster, Subplanck Foam is gained 20x faster, Subspatial Foam is gained 30x faster, etc.boolean(hikers_dream, and unlock a 29th & 30th energy upgrade)",
		172: "The Elementary Particle gain softcap is showNum(20)% weaker for every three OoMs of Elementaries done.",
		174: "The Perk Accelerator is showNum(5)% stronger.",
	}
};